#ifndef E2_REPORTING_E2BACKTESTSUMMARY_MQH
#define E2_REPORTING_E2BACKTESTSUMMARY_MQH
#include "E2Logger.mqh"
#include "..\\strategy\\E2OBRTypes.mqh"
#include "..\\risk\\E2PositionSizer.mqh"
class E2BacktestSummary
  {
private: E2Logger *m_logger;
public: E2BacktestSummary(void):m_logger(NULL){} void Initialize(E2Logger &logger){m_logger=&logger;}
   void CoreVerify(const bool initialized,const int candidates,const int requests,const int attempts,const int successes,const int registered,const int finalized,const int duplicate_execution_ids,const int duplicate_finalized,const int causality,const int ownership,const int unknown_positions)
     {if(m_logger==NULL)return;m_logger.Info("initialized="+IntegerToString((int)initialized)+", strategyCandidates="+IntegerToString(candidates)+", tradeRequests="+IntegerToString(requests)+", executionAttempts="+IntegerToString(attempts)+", executionSuccesses="+IntegerToString(successes)+", positionsRegistered="+IntegerToString(registered)+", finalizedTrades="+IntegerToString(finalized)+", duplicateExecutionIds="+IntegerToString(duplicate_execution_ids)+", duplicateFinalizedTrades="+IntegerToString(duplicate_finalized)+", causalityViolations="+IntegerToString(causality)+", ownershipViolations="+IntegerToString(ownership)+", unknownE2Positions="+IntegerToString(unknown_positions)+".","E2_CORE_VERIFY");}
   void OBRVerify(const E2OBRVerification &v)
     {if(m_logger==NULL)return;m_logger.Info("londonDaysObserved="+IntegerToString((int)v.london_days_observed)+", openingRangesComplete="+IntegerToString((int)v.opening_ranges_complete)+", openingRangesIncomplete="+IntegerToString((int)v.opening_ranges_incomplete)+", breakoutEligibleCandles="+IntegerToString((int)v.breakout_eligible_candles)+", longCloseBreakouts="+IntegerToString((int)v.long_close_breakouts)+", shortCloseBreakouts="+IntegerToString((int)v.short_close_breakouts)+", adxPass="+IntegerToString((int)v.adx_pass)+", rangeSizePass="+IntegerToString((int)v.range_size_pass)+", longGapPass="+IntegerToString((int)v.long_gap_pass)+", shortGapPass="+IntegerToString((int)v.short_gap_pass)+", longCandidates="+IntegerToString((int)v.long_candidates)+", shortCandidates="+IntegerToString((int)v.short_candidates)+", totalCandidates="+IntegerToString((int)v.total_candidates)+", duplicateCandidates="+IntegerToString((int)v.duplicate_candidates)+", causalityViolations="+IntegerToString((int)v.causality_violations)+".","OBR_VERIFY");}
   void OBRTimeVerify(const E2OBRTimeVerification &v)
     {if(m_logger==NULL)return;m_logger.Info("gmtDays="+IntegerToString((int)v.gmt_days)+", bstDays="+IntegerToString((int)v.bst_days)+", dstTransitionObservations="+IntegerToString((int)v.dst_transition_observations)+", orReconstructionSuccesses="+IntegerToString((int)v.or_reconstruction_successes)+", orReconstructionFailures="+IntegerToString((int)v.or_reconstruction_failures)+", orMutationViolations="+IntegerToString((int)v.or_mutation_violations)+", invalidOrBars="+IntegerToString((int)v.invalid_or_bars)+", dayResetViolations="+IntegerToString((int)v.day_reset_violations)+".","OBR_TIME_VERIFY");}
   void OBRPlanVerify(const E2OBRPlanVerification &v)
     {if(m_logger==NULL)return;m_logger.Info("candidatesReceived="+IntegerToString((int)v.candidates_received)+", entryWindowsReached="+IntegerToString((int)v.entry_windows_reached)+", expiredCandidates="+IntegerToString((int)v.expired_candidates)+", rejectedDayConsumed="+IntegerToString((int)v.rejected_day_consumed)+", rejectedEntryGap="+IntegerToString((int)v.rejected_entry_gap)+", rejectedStopGeometry="+IntegerToString((int)v.rejected_stop_geometry)+", rejectedPositionOpen="+IntegerToString((int)v.rejected_position_open)+", rejectedSpread="+IntegerToString((int)v.rejected_spread)+", rejectedQuote="+IntegerToString((int)v.rejected_quote)+", rejectedSizing="+IntegerToString((int)v.rejected_sizing)+", rejectedMargin="+IntegerToString((int)v.rejected_margin)+", rejectedOther="+IntegerToString((int)v.rejected_other)+", validExecutionRequests="+IntegerToString((int)v.valid_execution_requests)+", longRequests="+IntegerToString((int)v.long_requests)+", shortRequests="+IntegerToString((int)v.short_requests)+", duplicateRequests="+IntegerToString((int)v.duplicate_requests)+", planCausalityViolations="+IntegerToString((int)v.plan_causality_violations)+".","OBR_PLAN_VERIFY");}
   void OBRExecVerify(const E2OBRExecutionVerification &v)
     {if(m_logger==NULL)return;m_logger.Info("requestsReceived="+IntegerToString((int)v.requests_received)+", executionAttempts="+IntegerToString((int)v.execution_attempts)+", executionSuccesses="+IntegerToString((int)v.execution_successes)+", executionFailures="+IntegerToString((int)v.execution_failures)+", longAttempts="+IntegerToString((int)v.long_attempts)+", shortAttempts="+IntegerToString((int)v.short_attempts)+", successfulEntries="+IntegerToString((int)v.successful_entries)+", dayLocksCreated="+IntegerToString((int)v.day_locks_created)+", duplicateExecutionAttempts="+IntegerToString((int)v.duplicate_execution_attempts)+", unresolvedExecutionStates="+IntegerToString((int)v.unresolved_execution_states)+", registrationFailures="+IntegerToString((int)v.registration_failures)+", protectionFailures="+IntegerToString((int)v.protection_failures)+".","OBR_EXEC_VERIFY");}
   void OBRRecoveryVerify(const E2OBRRecoveryVerification &v)
     {if(m_logger==NULL)return;m_logger.Info("initializations="+IntegerToString((int)v.initializations)+", orRecoverySuccesses="+IntegerToString((int)v.or_recovery_successes)+", orRecoveryFailures="+IntegerToString((int)v.or_recovery_failures)+", dayLockRecoveries="+IntegerToString((int)v.day_lock_recoveries)+", openPositionRecoveries="+IntegerToString((int)v.open_position_recoveries)+", metadataRecoveryFailures="+IntegerToString((int)v.metadata_recovery_failures)+", duplicateDayEntryViolations="+IntegerToString((int)v.duplicate_day_entry_violations)+", originalRRecoveryViolations="+IntegerToString((int)v.original_r_recovery_violations)+".","OBR_RECOVERY_VERIFY");}
   void RiskVerify(const E2RiskModeVerification &v)
     {if(m_logger==NULL)return;m_logger.Info("tradesSized="+IntegerToString(v.trades_sized)+", fixedCashRequests="+IntegerToString(v.fixed_cash_requests)+", balancePercentRequests="+IntegerToString(v.balance_percent_requests)+", requestedMin="+DoubleToString(v.requested_min,2)+", requestedMax="+DoubleToString(v.requested_max,2)+", requestedAverage="+DoubleToString(v.trades_sized>0?v.requested_sum/v.trades_sized:0.0,2)+", actualInitialRiskMin="+DoubleToString(v.original_min,2)+", actualInitialRiskMax="+DoubleToString(v.original_max,2)+", invalidRiskRequests="+IntegerToString(v.invalid_risk_requests)+".","E2_RISK_VERIFY");}
  };
#endif
