#ifndef E2_REPORTING_E2BACKTESTSUMMARY_MQH
#define E2_REPORTING_E2BACKTESTSUMMARY_MQH

#include "E2Logger.mqh"
#include "..\\risk\\E2PositionSizer.mqh"
#include "..\\strategy\\E2StrategyTypes.mqh"

class E2BacktestSummary
  {
private:E2Logger *m_logger;
public:
   E2BacktestSummary(void):m_logger(NULL){}
   void Initialize(E2Logger &logger){m_logger=&logger;}
   void CoreVerify(const bool initialized,const int candidates,const int requests,const int attempts,const int successes,const int registered,const int finalized,const int duplicate_execution_ids,const int duplicate_finalized,const int causality,const int ownership,const int unknown_positions)
     {if(m_logger==NULL)return;m_logger.Info("initialized="+IntegerToString((int)initialized)+", strategyCandidates="+IntegerToString(candidates)+", tradeRequests="+IntegerToString(requests)+", executionAttempts="+IntegerToString(attempts)+", executionSuccesses="+IntegerToString(successes)+", positionsRegistered="+IntegerToString(registered)+", finalizedTrades="+IntegerToString(finalized)+", duplicateExecutionIds="+IntegerToString(duplicate_execution_ids)+", duplicateFinalizedTrades="+IntegerToString(duplicate_finalized)+", causalityViolations="+IntegerToString(causality)+", ownershipViolations="+IntegerToString(ownership)+", unknownE2Positions="+IntegerToString(unknown_positions)+".","E2_CORE_VERIFY");}
   void RiskVerify(const E2RiskModeVerification &v)
     {if(m_logger==NULL)return;int n=v.actual_risk_observations;m_logger.Info("tradesSized="+IntegerToString(v.trades_sized)+", actualRiskObservations="+IntegerToString(n)+", requestedAverage="+DoubleToString(v.trades_sized>0?v.requested_sum/v.trades_sized:0.0,2)+", actualInitialRiskAverage="+DoubleToString(n>0?v.original_sum/n:0.0,2)+", averageRiskDifference="+DoubleToString(n>0?v.difference_sum/n:0.0,2)+", actualRiskAboveRequested="+IntegerToString(v.actual_risk_above_requested)+", invalidRiskRequests="+IntegerToString(v.invalid_risk_requests)+".","E2_RISK_VERIFY");}
   void PlanVerify(const E2PlanVerification &v){if(m_logger!=NULL)m_logger.Info("candidatesReceived="+IntegerToString(v.candidates_received)+", requestsCreated="+IntegerToString(v.requests_created)+", expiredCandidates="+IntegerToString(v.expired_candidates)+", duplicateCandidates="+IntegerToString(v.duplicate_candidates)+", positionRejections="+IntegerToString(v.position_rejections)+", dayRejections="+IntegerToString(v.day_rejections)+", sizingRejections="+IntegerToString(v.sizing_rejections)+".","E2_PLAN_VERIFY");}
   void ExecVerify(const E2ExecutionVerification &v){if(m_logger!=NULL)m_logger.Info("attempts="+IntegerToString(v.attempts)+", successes="+IntegerToString(v.successes)+", failures="+IntegerToString(v.failures)+", unresolvedEntryDeals="+IntegerToString(v.unresolved_entry_deals)+", protectionFailures="+IntegerToString(v.protection_failures)+".","E2_EXEC_VERIFY");}
   void RVerify(const E2RVerification &v){if(m_logger!=NULL)m_logger.Info("newPositionsRegistered="+IntegerToString(v.new_positions_registered)+", recoveredPositionsValidated="+IntegerToString(v.recovered_positions_validated)+", targetsAttached="+IntegerToString(v.targets_attached)+", immutableRViolations="+IntegerToString(v.immutable_r_violations)+", invalidRGeometry="+IntegerToString(v.invalid_r_geometry)+".","E2_R_VERIFY");}
   void DayVerify(const E2DayVerification &v){if(m_logger!=NULL)m_logger.Info("enabled="+IntegerToString(v.enabled)+", historyLocksFound="+IntegerToString(v.history_locks_found)+", locksCreated="+IntegerToString(v.locks_created)+", candidatesSuppressed="+IntegerToString(v.candidates_suppressed)+", failedAttemptsLocked="+IntegerToString(v.failed_attempts_locked)+", historyRangeStart="+TimeToString(v.history_range_start,TIME_DATE|TIME_SECONDS)+", historyRangeEnd="+TimeToString(v.history_range_end,TIME_DATE|TIME_SECONDS)+", entryDealsScanned="+IntegerToString(v.entry_deals_scanned)+", ownedEntryDealsFound="+IntegerToString(v.owned_entry_deals_found)+", todayOwnedEntryDealsFound="+IntegerToString(v.today_owned_entry_deals_found)+", dailyLockRecovered="+IntegerToString(v.daily_lock_recovered)+", dailyLockFailureReason="+v.daily_lock_failure_reason+".","E2_DAY_VERIFY");}
   void DayAudit(const E2DayVerification &v){if(m_logger!=NULL)m_logger.Info("maxEntriesPerSymbolDay="+IntegerToString(v.max_entries_per_symbol_day)+", duplicateDayEntryViolations="+IntegerToString(v.duplicate_day_entry_violations)+", dayMappingViolations="+IntegerToString(v.day_mapping_violations)+".","E2_DAY_VERIFY");}
   void DayRecoveryDiag(const E2DayRecoveryDiagnostics &d){if(m_logger!=NULL)m_logger.Info("targetBrokerDate="+d.target_broker_date+", currentServerTime="+TimeToString(d.current_server_time,TIME_DATE|TIME_SECONDS)+", currentServerDate="+d.current_server_date+", latestOwnedEntryDeal="+StringFormat("%I64u",d.latest_owned_entry_deal)+", latestOwnedEntryDealTime="+TimeToString(d.latest_owned_entry_deal_time,TIME_DATE|TIME_SECONDS)+", latestOwnedEntryDealDate="+d.latest_owned_entry_deal_date+", ownedEntryDealsFound="+IntegerToString(d.owned_entry_deals_found)+", sameDateOwnedEntryDealsFound="+IntegerToString(d.same_date_owned_entry_deals_found)+", recoveredPositionEntryDeal="+StringFormat("%I64u",d.recovered_position_entry_deal)+", recoveredPositionEntryTime="+TimeToString(d.recovered_position_entry_time,TIME_DATE|TIME_SECONDS)+", recoveredPositionEntryDate="+d.recovered_position_entry_date+", dateComparisonResult="+d.date_comparison_result+", failureReason="+d.failure_reason+".","E2_DAY_RECOVERY_DIAG");}
   void RecoveryVerify(const E2RecoveryVerification &v){if(m_logger!=NULL)m_logger.Info("startupOpenPositions="+IntegerToString(v.startup_open_positions)+", statesLoaded="+IntegerToString(v.states_loaded)+", statesSaved="+IntegerToString(v.states_saved)+", statesCleared="+IntegerToString(v.states_cleared)+", recoveryFailures="+IntegerToString(v.recovery_failures)+", orphanStates="+IntegerToString(v.orphan_states)+".","E2_RECOVERY_VERIFY");}
   void RecoveryDiag(const E2RecoveryDiagnostics &d){if(m_logger!=NULL)m_logger.Info("stateFileExpected="+d.state_file_expected+", stateFileFound="+d.state_file_found+", fileOpenSuccess="+IntegerToString(d.file_open_success)+", fileOpenError="+IntegerToString(d.file_open_error)+", rowsRead="+IntegerToString(d.rows_read)+", validRowsParsed="+IntegerToString(d.valid_rows_parsed)+", symbolMatch="+IntegerToString(d.symbol_match)+", magicMatch="+IntegerToString(d.magic_match)+", positionIdentifierMatch="+IntegerToString(d.position_identifier_match)+", positionTicketMatch="+IntegerToString(d.position_ticket_match)+", directionMatch="+IntegerToString(d.direction_match)+", entryDealResolved="+IntegerToString(d.entry_deal_resolved)+", fillValid="+IntegerToString(d.fill_valid)+", initialSLValid="+IntegerToString(d.initial_sl_valid)+", originalRValid="+IntegerToString(d.original_r_valid)+", targetRValid="+IntegerToString(d.target_r_valid)+", tpValid="+IntegerToString(d.tp_valid)+", selectedRecoveryRecord="+d.selected_recovery_record+", recoveryFailureReason="+d.recovery_failure_reason+".","E2_RECOVERY_DIAG");}
   void RecoveryDiagFields(const E2RecoveryDiagnostics &d){if(m_logger!=NULL)m_logger.Info("fieldsRead="+IntegerToString(d.fields_read)+", expectedFields="+IntegerToString(d.expected_fields)+".","E2_RECOVERY_DIAG");}
   void RecoveryDiagComparisons(const E2RecoveryDiagnostics &d){if(m_logger!=NULL)m_logger.Info("originalRComparisonsPerformed="+IntegerToString(d.original_r_comparisons_performed)+", originalRMismatches="+IntegerToString(d.original_r_mismatches)+", slComparisonsPerformed="+IntegerToString(d.sl_comparisons_performed)+", slMismatches="+IntegerToString(d.sl_mismatches)+", tpComparisonsPerformed="+IntegerToString(d.tp_comparisons_performed)+", tpMismatches="+IntegerToString(d.tp_mismatches)+".","E2_RECOVERY_DIAG");}
   void ReconcileVerify(const E2ReconcileVerification &v){if(m_logger!=NULL)m_logger.Info("signalRows="+IntegerToString(v.signal_rows)+", uniqueSignalCandidateIds="+IntegerToString(v.unique_signal_candidate_ids)+", duplicateSignalRows="+IntegerToString(v.duplicate_signal_rows)+", tradeRows="+IntegerToString(v.trade_rows)+", uniqueTradeIds="+IntegerToString(v.unique_trade_ids)+", duplicateTradeRows="+IntegerToString(v.duplicate_trade_rows)+", totalCandidates="+IntegerToString(v.total_candidates)+", executedCandidates="+IntegerToString(v.executed_candidates)+", executionFailedCandidates="+IntegerToString(v.execution_failed_candidates)+", expiredCandidates="+IntegerToString(v.expired_candidates)+", positionRejectedCandidates="+IntegerToString(v.position_rejected_candidates)+", dayRejectedCandidates="+IntegerToString(v.day_rejected_candidates)+", sizingRejectedCandidates="+IntegerToString(v.sizing_rejected_candidates)+", safetyRejectedCandidates="+IntegerToString(v.safety_rejected_candidates)+", otherCandidateOutcomes="+IntegerToString(v.other_candidate_outcomes)+", candidateOutcomeSum="+IntegerToString(v.candidate_outcome_sum)+", tradeRequests="+IntegerToString(v.trade_requests)+", executionAttempts="+IntegerToString(v.execution_attempts)+", executionSuccesses="+IntegerToString(v.execution_successes)+", newPositionsRegistered="+IntegerToString(v.new_positions_registered)+", finalizedTrades="+IntegerToString(v.finalized_trades)+", orphanSignalRows="+IntegerToString(v.orphan_signal_rows)+", orphanTradeRows="+IntegerToString(v.orphan_trade_rows)+", missingSignalRows="+IntegerToString(v.missing_signal_rows)+", missingTradeRows="+IntegerToString(v.missing_trade_rows)+", writeFailures="+IntegerToString(v.write_failures)+", reconciliationViolations="+IntegerToString(v.reconciliation_violations)+".","XAU_SF_RECONCILE_VERIFY");}
   void FinancialVerify(const E2FinancialVerification &v){if(m_logger!=NULL)m_logger.Info("tradesChecked="+IntegerToString(v.trades_checked)+", grossProfitSum="+DoubleToString(v.gross_profit_sum,2)+", commissionSum="+DoubleToString(v.commission_sum,2)+", swapSum="+DoubleToString(v.swap_sum,2)+", feeSum="+DoubleToString(v.fee_sum,2)+", netProfitSum="+DoubleToString(v.net_profit_sum,2)+", mt5AuthoritativeProfitSum="+DoubleToString(v.mt5_authoritative_profit_sum,2)+", financialDifference="+DoubleToString(v.financial_difference,8)+", financialMismatchTrades="+IntegerToString(v.financial_mismatch_trades)+", invalidInitialRiskTrades="+IntegerToString(v.invalid_initial_risk_trades)+", invalidRealizedRTrades="+IntegerToString(v.invalid_realized_r_trades)+".","XAU_SF_FINANCIAL_VERIFY");}
   void SignalVerify(const string tag,const E2SignalVerification &v)
   {if(m_logger!=NULL)m_logger.Info("barsObserved="+IntegerToString(v.bars_observed)+", candidates="+IntegerToString(v.total_candidates)+", long="+IntegerToString(v.long_candidates)+", short="+IntegerToString(v.short_candidates)+", timeFailures="+IntegerToString(v.time_failures)+".",tag);}
};
#endif
