#ifndef E2_REPORTING_E2BACKTESTSUMMARY_MQH
#define E2_REPORTING_E2BACKTESTSUMMARY_MQH
#include "E2Logger.mqh"
#include "..\\strategy\\E2OBRTypes.mqh"
#include "..\\risk\\E2PositionSizer.mqh"
class E2BacktestSummary
  {
private: E2Logger *m_logger;
public: E2BacktestSummary(void):m_logger(NULL){} void Initialize(E2Logger &logger){m_logger=&logger;}
   void CoreVerify(const bool initialized,const int candidates,const int requests,const int attempts,const int successes,const int registered,const int finalized,const int duplicate_execution_ids,const int duplicate_finalized,const int causality,const int ownership,const int unknown_positions)
     {if(m_logger==NULL)return;m_logger.Info("initialized="+IntegerToString((int)initialized)+", strategyCandidates="+IntegerToString(candidates)+", tradeRequests="+IntegerToString(requests)+", executionAttempts="+IntegerToString(attempts)+", executionSuccesses="+IntegerToString(successes)+", positionsRegistered="+IntegerToString(registered)+", finalizedTrades="+IntegerToString(finalized)+", duplicateExecutionIds="+IntegerToString(duplicate_execution_ids)+", duplicateFinalizedTrades="+IntegerToString(duplicate_finalized)+", causalityViolations="+IntegerToString(causality)+", ownershipViolations="+IntegerToString(ownership)+", unknownE2Positions="+IntegerToString(unknown_positions)+".","E2_CORE_VERIFY");}
   void OBRVerify(const E2OBRVerification &v)
     {if(m_logger==NULL)return;m_logger.Info("londonDaysObserved="+IntegerToString((int)v.london_days_observed)+", openingRangesComplete="+IntegerToString((int)v.opening_ranges_complete)+", openingRangesIncomplete="+IntegerToString((int)v.opening_ranges_incomplete)+", breakoutEligibleCandles="+IntegerToString((int)v.breakout_eligible_candles)+", longCloseBreakouts="+IntegerToString((int)v.long_close_breakouts)+", shortCloseBreakouts="+IntegerToString((int)v.short_close_breakouts)+", adxPass="+IntegerToString((int)v.adx_pass)+", rangeSizePass="+IntegerToString((int)v.range_size_pass)+", longGapPass="+IntegerToString((int)v.long_gap_pass)+", shortGapPass="+IntegerToString((int)v.short_gap_pass)+", longCandidates="+IntegerToString((int)v.long_candidates)+", shortCandidates="+IntegerToString((int)v.short_candidates)+", totalCandidates="+IntegerToString((int)v.total_candidates)+", duplicateCandidates="+IntegerToString((int)v.duplicate_candidates)+", causalityViolations="+IntegerToString((int)v.causality_violations)+".","OBR_VERIFY");}
   void OBRTimeVerify(const E2OBRTimeVerification &v)
     {if(m_logger==NULL)return;m_logger.Info("gmtDays="+IntegerToString((int)v.gmt_days)+", bstDays="+IntegerToString((int)v.bst_days)+", dstTransitionObservations="+IntegerToString((int)v.dst_transition_observations)+", orReconstructionSuccesses="+IntegerToString((int)v.or_reconstruction_successes)+", orReconstructionFailures="+IntegerToString((int)v.or_reconstruction_failures)+", orMutationViolations="+IntegerToString((int)v.or_mutation_violations)+", invalidOrBars="+IntegerToString((int)v.invalid_or_bars)+", dayResetViolations="+IntegerToString((int)v.day_reset_violations)+".","OBR_TIME_VERIFY");}
   void OBRPlanVerify(const E2OBRPlanVerification &v)
     {if(m_logger==NULL)return;m_logger.Info("candidatesReceived="+IntegerToString((int)v.candidates_received)+", entryWindowsReached="+IntegerToString((int)v.entry_windows_reached)+", expiredCandidates="+IntegerToString((int)v.expired_candidates)+", rejectedDayConsumed="+IntegerToString((int)v.rejected_day_consumed)+", rejectedEntryGap="+IntegerToString((int)v.rejected_entry_gap)+", rejectedStopGeometry="+IntegerToString((int)v.rejected_stop_geometry)+", rejectedPositionOpen="+IntegerToString((int)v.rejected_position_open)+", rejectedSpread="+IntegerToString((int)v.rejected_spread)+", rejectedQuote="+IntegerToString((int)v.rejected_quote)+", rejectedSizing="+IntegerToString((int)v.rejected_sizing)+", rejectedMargin="+IntegerToString((int)v.rejected_margin)+", rejectedOther="+IntegerToString((int)v.rejected_other)+", validExecutionRequests="+IntegerToString((int)v.valid_execution_requests)+", longRequests="+IntegerToString((int)v.long_requests)+", shortRequests="+IntegerToString((int)v.short_requests)+", duplicateRequests="+IntegerToString((int)v.duplicate_requests)+", planCausalityViolations="+IntegerToString((int)v.plan_causality_violations)+".","OBR_PLAN_VERIFY");}
   void OBRExecVerify(const E2OBRExecutionVerification &v)
     {if(m_logger==NULL)return;m_logger.Info("requestsReceived="+IntegerToString((int)v.requests_received)+", executionAttempts="+IntegerToString((int)v.execution_attempts)+", executionSuccesses="+IntegerToString((int)v.execution_successes)+", executionFailures="+IntegerToString((int)v.execution_failures)+", longAttempts="+IntegerToString((int)v.long_attempts)+", shortAttempts="+IntegerToString((int)v.short_attempts)+", successfulEntries="+IntegerToString((int)v.successful_entries)+", dayLocksCreated="+IntegerToString((int)v.day_locks_created)+", duplicateExecutionAttempts="+IntegerToString((int)v.duplicate_execution_attempts)+", unresolvedExecutionStates="+IntegerToString((int)v.unresolved_execution_states)+", registrationFailures="+IntegerToString((int)v.registration_failures)+", protectionFailures="+IntegerToString((int)v.protection_failures)+".","OBR_EXEC_VERIFY");}
   void OBRRecoveryVerify(const E2OBRRecoveryVerification &v)
     {if(m_logger==NULL)return;m_logger.Info("initializations="+IntegerToString((int)v.initializations)+", orRecoverySuccesses="+IntegerToString((int)v.or_recovery_successes)+", orRecoveryFailures="+IntegerToString((int)v.or_recovery_failures)+", dayLockRecoveries="+IntegerToString((int)v.day_lock_recoveries)+", openPositionRecoveries="+IntegerToString((int)v.open_position_recoveries)+", metadataRecoveryFailures="+IntegerToString((int)v.metadata_recovery_failures)+", duplicateDayEntryViolations="+IntegerToString((int)v.duplicate_day_entry_violations)+", originalRRecoveryViolations="+IntegerToString((int)v.original_r_recovery_violations)+".","OBR_RECOVERY_VERIFY");}
   void RiskVerify(const E2RiskModeVerification &v)
     {if(m_logger==NULL)return;m_logger.Info("tradesSized="+IntegerToString(v.trades_sized)+", fixedCashRequests="+IntegerToString(v.fixed_cash_requests)+", balancePercentRequests="+IntegerToString(v.balance_percent_requests)+", requestedMin="+DoubleToString(v.requested_min,2)+", requestedMax="+DoubleToString(v.requested_max,2)+", requestedAverage="+DoubleToString(v.trades_sized>0?v.requested_sum/v.trades_sized:0.0,2)+", actualInitialRiskMin="+DoubleToString(v.original_min,2)+", actualInitialRiskMax="+DoubleToString(v.original_max,2)+", actualInitialRiskAverage="+DoubleToString(v.trades_sized>0?v.original_sum/v.trades_sized:0.0,2)+", minimumRiskDifference="+DoubleToString(v.difference_min,2)+", maximumRiskDifference="+DoubleToString(v.difference_max,2)+", averageRiskDifference="+DoubleToString(v.trades_sized>0?v.difference_sum/v.trades_sized:0.0,2)+", actualRiskAboveRequested="+IntegerToString(v.actual_risk_above_requested)+", riskModeMismatch="+IntegerToString(v.risk_mode_mismatch)+", invalidRiskRequests="+IntegerToString(v.invalid_risk_requests)+".","E2_RISK_VERIFY");}
   void ReconcileVerify(const E2OBRReconcileVerification &v){if(m_logger==NULL)return;m_logger.Info("candidateCount="+IntegerToString((int)v.candidate_count)+", planCandidateCount="+IntegerToString((int)v.plan_candidate_count)+", validRequestCount="+IntegerToString((int)v.valid_request_count)+", executionAttemptCount="+IntegerToString((int)v.execution_attempt_count)+", successfulEntryCount="+IntegerToString((int)v.successful_entry_count)+", registeredPositionCount="+IntegerToString((int)v.registered_position_count)+", finalizedTradeCount="+IntegerToString((int)v.finalized_trade_count)+", tradeCsvRows="+IntegerToString((int)v.trade_csv_rows)+", uniqueTradeIds="+IntegerToString((int)v.unique_trade_ids)+", uniqueCandidateIdsForTrades="+IntegerToString((int)v.unique_candidate_ids_for_trades)+", dayLocksCreated="+IntegerToString((int)v.day_locks_created)+", uniqueSuccessfulSymbolDays="+IntegerToString((int)v.unique_successful_symbol_days)+", duplicateTradeIds="+IntegerToString((int)v.duplicate_trade_ids)+", duplicateSuccessfulSymbolDays="+IntegerToString((int)v.duplicate_successful_symbol_days)+", orphanExecutions="+IntegerToString((int)v.orphan_executions)+", orphanRegistrations="+IntegerToString((int)v.orphan_registrations)+", orphanFinalizations="+IntegerToString((int)v.orphan_finalizations)+", missingCandidateLinks="+IntegerToString((int)v.missing_candidate_links)+", missingExecutionLinks="+IntegerToString((int)v.missing_execution_links)+", tradeCountMismatch="+IntegerToString((int)v.trade_count_mismatch)+".","OBR_RECONCILE_VERIFY");}
   void FinancialVerify(const E2OBRFinancialVerification &v){if(m_logger==NULL)return;m_logger.Info("grossProfit="+DoubleToString(v.gross_profit,2)+", commission="+DoubleToString(v.commission,2)+", swap="+DoubleToString(v.swap,2)+", fees="+DoubleToString(v.fees,2)+", netProfit="+DoubleToString(v.net_profit,2)+", netR="+DoubleToString(v.net_r,6)+", wins="+IntegerToString((int)v.wins)+", losses="+IntegerToString((int)v.losses)+", breakevens="+IntegerToString((int)v.breakevens)+", winRate="+DoubleToString(v.win_rate,4)+", averageR="+DoubleToString(v.average_r,6)+", averageWinR="+DoubleToString(v.average_win_r,6)+", averageLossR="+DoubleToString(v.average_loss_r,6)+", profitFactorR="+DoubleToString(v.profit_factor_r,6)+", maximumDrawdownR="+DoubleToString(v.maximum_drawdown_r,6)+", profitDifference="+DoubleToString(v.profit_difference,2)+", rDifference="+DoubleToString(v.r_difference,6)+", tradeCountDifference="+IntegerToString((int)v.trade_count_difference)+".","OBR_FINANCIAL_VERIFY");}
   void RVerify(const E2OBRRVerification &v){if(m_logger==NULL)return;m_logger.Info("tradesChecked="+IntegerToString((int)v.trades_checked)+", invalidOriginalR="+IntegerToString((int)v.invalid_original_r)+", originalRMismatches="+IntegerToString((int)v.original_r_mismatches)+", tpGeometryMismatches="+IntegerToString((int)v.tp_geometry_mismatches)+", nonPositiveOriginalR="+IntegerToString((int)v.non_positive_original_r)+", originalRMutationViolations="+IntegerToString((int)v.original_r_mutation_violations)+", maximumTpDifferenceTicks="+DoubleToString(v.maximum_tp_difference_ticks,4)+".","OBR_R_VERIFY");}
   void DayVerify(const E2OBRDayVerification &v){if(m_logger==NULL)return;m_logger.Info("successfulEntries="+IntegerToString((int)v.successful_entries)+", uniqueSuccessfulDays="+IntegerToString((int)v.unique_successful_days)+", maxEntriesPerSymbolLondonDay="+IntegerToString((int)v.max_entries_per_symbol_london_day)+", duplicateSuccessfulDays="+IntegerToString((int)v.duplicate_successful_days)+", dayLocksCreated="+IntegerToString((int)v.day_locks_created)+", dayLockMismatch="+IntegerToString((int)v.day_lock_mismatch)+".","OBR_DAY_VERIFY");}
   void EntryTimeVerify(const E2OBREntryTimeVerification &v){if(m_logger==NULL)return;m_logger.Info("attemptsChecked="+IntegerToString((int)v.attempts_checked)+", correctNextBarAttempts="+IntegerToString((int)v.correct_next_bar_attempts)+", sameBarViolations="+IntegerToString((int)v.same_bar_violations)+", lateEntryViolations="+IntegerToString((int)v.late_entry_violations)+", earlyEntryViolations="+IntegerToString((int)v.early_entry_violations)+", missingCandidateTimestamp="+IntegerToString((int)v.missing_candidate_timestamp)+", entryTimeViolations="+IntegerToString((int)v.entry_time_violations)+".","OBR_ENTRY_TIME_VERIFY");}
   void EntryGapVerify(const E2OBREntryGapVerification &v){if(m_logger==NULL)return;m_logger.Info("acceptedChecked="+IntegerToString((int)v.accepted_checked)+", rejectedChecked="+IntegerToString((int)v.rejected_checked)+", falseAccepts="+IntegerToString((int)v.false_accepts)+", falseRejects="+IntegerToString((int)v.false_rejects)+", atrMutationViolations="+IntegerToString((int)v.atr_mutation_violations)+", gapDecisionViolations="+IntegerToString((int)v.gap_decision_violations)+".","OBR_ENTRY_GAP_VERIFY");}
  };
#endif
