#ifndef E2_REPORTING_E2TRADEREPORTER_MQH
#define E2_REPORTING_E2TRADEREPORTER_MQH
#include "E2CsvExporter.mqh"
#include "..\\strategy\\E2StrategyTypes.mqh"
#include "..\\execution\\E2OrderExecutor.mqh"

struct E2SignalReport
  {E2Candidate c;E2PlanningAudit p;double o,h,l;string status,reason,final_trade_status;ulong order,deal,position;double fill,original_r,target_r,tp;int recovery;};
struct E2TradeReport
  {E2PositionMetadata m;int signal_index,recovery_count,finalized;ulong order;datetime exit_time;double exit_price,gross,commission,swap,fee,net,realized_r;int exit_deals;string exit_reason,status,flags;};

class E2TradeReporter
  {
private:
   ulong m_magic;bool m_csv_enabled;E2Logger *m_logger;E2Config m_config;string m_symbol,m_mode,m_hash,m_run_id,m_schema,m_signal_file,m_trade_file;datetime m_run_start,m_first_time,m_last_time;E2SignalReport m_signals[];E2TradeReport m_trades[];int m_duplicates,m_duplicate_finals,m_causality,m_write_failures,m_collision_checks,m_collisions_avoided,m_file_suffix;E2ReconcileVerification m_reconcile;E2FinancialVerification m_financial;
   int FindSignal(const string id)const{for(int i=0;i<ArraySize(m_signals);i++)if(m_signals[i].c.candidate_id==id)return(i);return(-1);}int FindPosition(const ulong id)const{for(int i=0;i<ArraySize(m_trades);i++)if(m_trades[i].m.position_id==id)return(i);return(-1);}
   string TS(const datetime t)const{if(t<=0)return("");string s=TimeToString(t,TIME_DATE|TIME_SECONDS);StringReplace(s,".","-");return(s);}string N(const double v,const int d=10)const{return(DoubleToString(v,d));}
   string Safe(string s)const{StringReplace(s,"/","_");StringReplace(s,"\\","_");StringReplace(s,".","_");return(s);}
   uint HashText(const string value)const{uint h=2166136261;for(int i=0;i<StringLen(value);i++){h^=(uint)StringGetCharacter(value,i);h*=16777619;}return(h);}
   string ConfigText()const{return("LONDON_RANGE_BREAKOUT"+"|"+"1.0"+"|"+m_symbol+"|"+"M5"+"|"+IntegerToString((int)m_config.range_start)+"|"+IntegerToString((int)m_config.range_end)+"|"+IntegerToString((int)m_config.breakout_start)+"|"+IntegerToString((int)m_config.breakout_end)+"|"+IntegerToString((int)m_config.stop_mode)+"|"+IntegerToString((int)m_config.atr_length)+"|"+N(m_config.atr_multiplier)+"|"+N(m_config.target_r)+"|"+IntegerToString((int)m_config.one_trade_per_day)+"|"+m_config.time_policy_digest+"|"+IntegerToString((int)m_config.risk_mode)+"|"+N(m_config.fixed_cash_risk)+"|"+N(m_config.balance_risk_percent)+"|"+StringFormat("%I64u",m_config.expert_magic_number)+"|"+IntegerToString((int)m_config.trading_enabled)+"|"+N(m_config.max_spread_pips)+"|"+N(m_config.max_entry_deviation_pips)+"|"+IntegerToString((int)m_config.max_quote_age_seconds)+"|"+IntegerToString((int)m_config.minimum_seconds_between_executions)+"|"+IntegerToString((int)m_config.weekend_flat_enabled)+"|"+IntegerToString((int)m_config.weekend_flat_minutes_before_session_close));}
   string PeriodText()const{if(m_mode!="TESTER")return("CONTINUOUS");if(m_first_time<=0||m_last_time<=0)return("EFFECTIVE_UNKNOWN");string a=TimeToString(m_first_time,TIME_DATE),b=TimeToString(m_last_time,TIME_DATE);StringReplace(a,".","");StringReplace(b,".","");return(a+"-"+b);}
   string ExitReason(const ENUM_DEAL_REASON r)const{if(r==DEAL_REASON_TP)return("TP");if(r==DEAL_REASON_SL)return("SL");if(r==DEAL_REASON_SO)return("SO");if(r==DEAL_REASON_EXPERT)return("EXPERT");if(r==DEAL_REASON_CLIENT||r==DEAL_REASON_MOBILE||r==DEAL_REASON_WEB)return("MANUAL");return("OTHER");}
   void Add(const string value,string &row[]){int n=ArraySize(row);ArrayResize(row,n+1);row[n]=value;}
   bool UniqueSignal(const int i)const{for(int j=0;j<i;j++)if(m_signals[j].c.candidate_id==m_signals[i].c.candidate_id)return(false);return(true);}bool UniqueTrade(const int i)const{for(int j=0;j<i;j++)if(m_trades[j].m.position_id==m_trades[i].m.position_id)return(false);return(true);}
   bool ResolveReportPair()
     {
      string day=TimeToString(m_run_start,TIME_DATE);
      StringReplace(day,".","");
      string mmdd=StringSubstr(day,4,4);
      string base="E2_"+Safe(m_symbol)+"_"+mmdd+"_"+StringSubstr(m_hash,0,4);
      m_signal_file="";m_trade_file="";m_file_suffix=0;
      for(int sequence=1;sequence<=9999;sequence++)
        {
         m_collision_checks++;
         string suffix=(sequence==1?"":"_"+IntegerToString(sequence));
         string signal="E2\\Reports\\"+base+suffix+"_S.csv";
         string trade="E2\\Reports\\"+base+suffix+"_T.csv";
         if(!FileIsExist(signal,FILE_COMMON) && !FileIsExist(trade,FILE_COMMON))
           {
            m_signal_file=signal;m_trade_file=trade;m_file_suffix=sequence;
            m_logger.Info("signalFile="+m_signal_file+", tradeFile="+m_trade_file+", collisionChecks="+IntegerToString(m_collision_checks)+", collisionsAvoided="+IntegerToString(m_collisions_avoided)+", sharedSuffix="+(sequence==1?"NONE":IntegerToString(sequence))+", fullRunId="+m_run_id+", fullConfigHash="+m_hash+", hash4="+StringSubstr(m_hash,0,4),"LRB_REPORT_FILES");
            return(true);
           }
         m_collisions_avoided++;
        }
      m_write_failures++;
      m_logger.Error("reason=PAIR_NAMESPACE_EXHAUSTED, collisionChecks="+IntegerToString(m_collision_checks)+", collisionsAvoided="+IntegerToString(m_collisions_avoided),"LRB_REPORT_FILES");
      return(false);
     }
   void SignalHeader(string &r[]){string x[]={"schema_version","run_id","config_hash","candidate_id","strategy","symbol","timeframe","direction","london_day","range_start_london","range_end_london","range_high","range_low","range_width","signal_bar_time","signal_known_time","signal_close","breakout_distance","candidate_status","candidate_reason","planning_time","planning_bid","planning_ask","planning_spread","raw_sl","submitted_sl","sl_adjusted","sl_adjustment_distance","requested_cash_risk","calculated_volume","execution_id","entry_deal_ticket","position_identifier","actual_fill","original_r","target_r","submitted_tp","final_trade_status","recovery_involved"};ArrayCopy(r,x);}
   void SignalRow(const E2SignalReport &s,string &r[]){ArrayResize(r,0);Add(m_schema,r);Add(m_run_id,r);Add(m_hash,r);Add(s.c.candidate_id,r);Add("LONDON_RANGE_BREAKOUT",r);Add(s.c.symbol,r);Add("M5",r);Add(E2TradeDirectionName(s.c.direction),r);Add(IntegerToString(s.c.london_day),r);Add(TS(s.c.range_start_london),r);Add(TS(s.c.range_end_london),r);Add(N(s.c.range_high),r);Add(N(s.c.range_low),r);Add(N(s.c.range_high-s.c.range_low),r);Add(TS(s.c.signal_bar_time),r);Add(TS(s.c.signal_known_time),r);Add(N(s.c.signal_close),r);Add(N(s.c.breakout_distance),r);Add(s.status,r);Add(s.reason,r);Add(TS(s.p.planning_time),r);Add(N(s.p.planning_bid),r);Add(N(s.p.planning_ask),r);Add(N(s.p.planning_spread),r);Add(N(s.p.raw_sl),r);Add(N(s.p.submitted_sl),r);Add(IntegerToString(s.p.sl_adjusted),r);Add(N(s.p.sl_adjustment_distance),r);Add(N(s.p.requested_cash_risk),r);Add(N(s.p.calculated_volume),r);Add(s.p.execution_id,r);Add(StringFormat("%I64u",s.deal),r);Add(StringFormat("%I64u",s.position),r);Add(N(s.fill),r);Add(N(s.original_r),r);Add(N(s.target_r),r);Add(N(s.tp),r);Add(s.final_trade_status,r);Add(IntegerToString(s.recovery),r);}
   void TradeHeader(string &r[]){string x[]={"schema_version","run_id","config_hash","trade_id","candidate_id","execution_id","strategy","symbol","timeframe","direction","london_day","range_start_london","range_end_london","range_high","range_low","range_width","signal_bar_time","signal_close","breakout_distance","time_policy_digest","planning_time","planning_bid","planning_ask","planning_spread","raw_sl","submitted_initial_sl","sl_adjusted","sl_adjustment_distance","risk_mode","requested_cash_risk","calculated_volume","entry_deal_ticket","position_identifier","fill_time","actual_fill","filled_volume","actual_initial_cash_risk","original_r","target_r","submitted_tp","recovery_involved","recovery_count","exit_time","exit_price","exit_reason","exit_deal_count","gross_profit","commission","swap","fee","net_profit","realized_r","trade_status","integrity_flags"};ArrayCopy(r,x);}
   void TradeRow(const E2TradeReport &t,string &r[]){ArrayResize(r,0);E2SignalReport s;ZeroMemory(s);if(t.signal_index>=0)s=m_signals[t.signal_index];Add(m_schema,r);Add(m_run_id,r);Add(m_hash,r);Add("E2|"+StringFormat("%I64u",t.m.position_id),r);Add(t.m.candidate_id,r);Add(t.m.execution_id,r);Add((t.m.london_day>0?"LONDON_RANGE_BREAKOUT":"LEGACY_RECOVERED"),r);Add(t.m.symbol,r);Add("M5",r);Add(E2TradeDirectionName(t.m.direction),r);Add(IntegerToString(t.m.london_day),r);Add(TS(t.m.range_start_london),r);Add(TS(t.m.range_end_london),r);Add(N(t.m.range_high),r);Add(N(t.m.range_low),r);Add(N(t.m.range_high-t.m.range_low),r);Add(TS(t.m.signal_time),r);Add(N(t.m.signal_close),r);Add(N(t.m.breakout_distance),r);Add(t.m.time_policy_digest,r);Add(TS(s.p.planning_time),r);Add(N(s.p.planning_bid),r);Add(N(s.p.planning_ask),r);Add(N(s.p.planning_spread),r);Add(N(s.p.raw_sl),r);Add(N(t.m.submitted_stop),r);Add(IntegerToString(s.p.sl_adjusted),r);Add(N(s.p.sl_adjustment_distance),r);Add((m_config.risk_mode==E2_RISK_FIXED_CASH?"FIXED_CASH":"BALANCE_PERCENT"),r);Add(N(t.m.requested_risk_cash),r);Add(N(t.m.volume),r);Add(StringFormat("%I64u",t.m.entry_deal),r);Add(StringFormat("%I64u",t.m.position_id),r);Add(TS(t.m.entry_time),r);Add(N(t.m.fill_price),r);Add(N(t.m.volume),r);Add(N(t.m.actual_risk_cash),r);Add(N(t.m.original_r),r);Add(N(t.m.target_r),r);Add(N(t.m.target_price),r);Add(IntegerToString(t.recovery_count>0),r);Add(IntegerToString(t.recovery_count),r);Add(TS(t.exit_time),r);Add(N(t.exit_price),r);Add(t.exit_reason,r);Add(IntegerToString(t.exit_deals),r);Add(N(t.gross,2),r);Add(N(t.commission,2),r);Add(N(t.swap,2),r);Add(N(t.fee,2),r);Add(N(t.net,2),r);Add(N(t.realized_r,6),r);Add(t.status,r);Add(t.flags,r);}
public:
   E2TradeReporter(void):m_magic(0),m_csv_enabled(false),m_logger(NULL),m_symbol(""),m_mode("UNKNOWN"),m_hash(""),m_run_id(""),m_schema("LRB_REPORT_V1"),m_signal_file(""),m_trade_file(""),m_run_start(0),m_first_time(0),m_last_time(0),m_duplicates(0),m_duplicate_finals(0),m_causality(0),m_write_failures(0),m_collision_checks(0),m_collisions_avoided(0),m_file_suffix(0){ZeroMemory(m_reconcile);ZeroMemory(m_financial);}
   bool Initialize(const E2Config &c,const string symbol,E2Logger &logger){m_config=c;m_csv_enabled=c.csv_export_enabled;m_magic=c.expert_magic_number;m_symbol=symbol;m_logger=&logger;ArrayResize(m_signals,0);ArrayResize(m_trades,0);m_duplicates=0;m_duplicate_finals=0;m_causality=0;m_write_failures=0;m_collision_checks=0;m_collisions_avoided=0;m_file_suffix=0;m_signal_file="";m_trade_file="";m_first_time=0;m_last_time=0;ZeroMemory(m_reconcile);ZeroMemory(m_financial);if(MQLInfoInteger(MQL_TESTER))m_mode="TESTER";else{ENUM_ACCOUNT_TRADE_MODE a=(ENUM_ACCOUNT_TRADE_MODE)AccountInfoInteger(ACCOUNT_TRADE_MODE);m_mode=(a==ACCOUNT_TRADE_MODE_DEMO?"DEMO":(a==ACCOUNT_TRADE_MODE_REAL?"LIVE":"UNKNOWN"));}m_hash=StringFormat("%08X",HashText(ConfigText()));datetime now=TimeCurrent();m_run_start=now;string stamp=TimeToString(now,TIME_DATE|TIME_SECONDS);StringReplace(stamp,".","");StringReplace(stamp,":","");StringReplace(stamp," ","-");m_run_id=stamp+"_"+m_hash;logger.Info("STRATEGY=LONDON_RANGE_BREAKOUT, RANGE_LONDON="+StringFormat("%02d:%02d-%02d:%02d",c.range_start/60,c.range_start%60,c.range_end/60,c.range_end%60)+", BREAKOUT_LONDON="+StringFormat("%02d:%02d-%02d:%02d",c.breakout_start/60,c.breakout_start%60,c.breakout_end/60,c.breakout_end%60)+", STOP_MODE="+EnumToString(c.stop_mode)+", ATR_LENGTH="+IntegerToString(c.atr_length)+", ATR_MULTIPLIER="+N(c.atr_multiplier)+", TARGET_R="+N(c.target_r)+", ONE_TRADE_PER_DAY="+(c.one_trade_per_day?"true":"false")+", WEEKEND_FLAT="+(c.weekend_flat_enabled?"true":"false")+", CONFIG_HASH="+m_hash+", timePolicyDigest="+c.time_policy_digest+", behavioralFields=25.","LRB_RUN_CONFIG");return(true);}
   void ObserveBar(const datetime t){if(t<=0)return;if(m_first_time==0||t<m_first_time)m_first_time=t;if(t>m_last_time)m_last_time=t;}
   void BeginCandidate(const E2Candidate &c){if(FindSignal(c.candidate_id)>=0){m_duplicates++;return;}E2SignalReport s;ZeroMemory(s);s.c=c;s.status="OTHER_REJECTED";s.reason="OUTCOME_PENDING";s.final_trade_status="NONE";MqlRates b[];if(CopyRates(c.symbol,PERIOD_M5,c.signal_bar_time,1,b)==1){s.o=b[0].open;s.h=b[0].high;s.l=b[0].low;}int n=ArraySize(m_signals);ArrayResize(m_signals,n+1);m_signals[n]=s;ObserveBar(c.signal_bar_time);}
   void RecordPlanning(const string id,const E2PlanningAudit &a){int i=FindSignal(id);if(i<0)return;m_signals[i].p=a;m_signals[i].status=a.status;m_signals[i].reason=a.reason;}
   void RecordExecutionFailure(const string id,const E2ExecutionResult &e){int i=FindSignal(id);if(i<0)return;m_signals[i].status=(e.status==E2_EXECUTION_POSITION_ALREADY_OPEN||e.status==E2_EXECUTION_PENDING_ORDER_EXISTS||e.status==E2_EXECUTION_DIRECTION_CONFLICT?"POSITION_REJECTED":(e.status==E2_EXECUTION_ORDER_REJECTED||e.status==E2_EXECUTION_FAILED?"EXECUTION_FAILED":"SAFETY_REJECTED"));m_signals[i].reason=E2ExecutionStatusName(e.status);}
   bool Register(const E2PositionMetadata &m,const bool recovered=false){int i=FindPosition(m.position_id);if(i>=0){if(recovered)m_trades[i].recovery_count++;else m_duplicates++;return(recovered);}E2TradeReport t;ZeroMemory(t);t.m=m;t.signal_index=FindSignal(m.candidate_id);t.recovery_count=(recovered?1:0);t.status="OPEN";t.flags="NONE";int n=ArraySize(m_trades);ArrayResize(m_trades,n+1);m_trades[n]=t;if(m.entry_time<m.signal_time)m_causality++;return(true);}
   void MarkExitReason(const ulong position_id,const string reason){int i=FindPosition(position_id);if(i>=0&&!m_trades[i].finalized)m_trades[i].exit_reason=reason;}
   void RecordExecuted(const string id,const E2ExecutionResult &e,const E2PositionMetadata &m){int s=FindSignal(id);int t=FindPosition(m.position_id);if(s>=0){m_signals[s].status="EXECUTED";m_signals[s].reason="ENTRY_FILLED";m_signals[s].order=e.order_ticket;m_signals[s].deal=m.entry_deal;m_signals[s].position=m.position_id;m_signals[s].fill=m.fill_price;m_signals[s].original_r=m.original_r;m_signals[s].target_r=m.target_r;m_signals[s].tp=m.target_price;m_signals[s].final_trade_status="OPEN";}if(t>=0){m_trades[t].order=e.order_ticket;m_trades[t].signal_index=s;}}
   void Reconcile(){if(!HistorySelect(0,TimeCurrent()+1))return;for(int i=0;i<ArraySize(m_trades);i++){if(m_trades[i].finalized)continue;bool open=false;for(int p=0;p<PositionsTotal();p++){ulong x=PositionGetTicket(p);if(x>0&&(ulong)PositionGetInteger(POSITION_IDENTIFIER)==m_trades[i].m.position_id){open=true;break;}}if(open)continue;double gross=0,commission=0,swap=0,fee=0;datetime exit_time=0;double exit_price=0;int exits=0;string reason=(StringLen(m_trades[i].exit_reason)>0?m_trades[i].exit_reason:"OTHER");for(int d=0;d<HistoryDealsTotal();d++){ulong deal=HistoryDealGetTicket(d);if(deal==0||(ulong)HistoryDealGetInteger(deal,DEAL_POSITION_ID)!=m_trades[i].m.position_id)continue;gross+=HistoryDealGetDouble(deal,DEAL_PROFIT);commission+=HistoryDealGetDouble(deal,DEAL_COMMISSION);swap+=HistoryDealGetDouble(deal,DEAL_SWAP);fee+=HistoryDealGetDouble(deal,DEAL_FEE);ENUM_DEAL_ENTRY e=(ENUM_DEAL_ENTRY)HistoryDealGetInteger(deal,DEAL_ENTRY);if(e==DEAL_ENTRY_OUT||e==DEAL_ENTRY_OUT_BY){exits++;datetime tm=(datetime)HistoryDealGetInteger(deal,DEAL_TIME);if(tm>=exit_time){exit_time=tm;exit_price=HistoryDealGetDouble(deal,DEAL_PRICE);if(StringLen(m_trades[i].exit_reason)==0)reason=ExitReason((ENUM_DEAL_REASON)HistoryDealGetInteger(deal,DEAL_REASON));}}}if(exit_time>0){E2TradeReport t=m_trades[i];t.gross=gross;t.commission=commission;t.swap=swap;t.fee=fee;t.net=gross+commission+swap+fee;t.exit_time=exit_time;t.exit_price=exit_price;t.exit_deals=exits;t.exit_reason=reason;t.realized_r=(t.m.actual_risk_cash>0?t.net/t.m.actual_risk_cash:0);t.status="FINALIZED";t.finalized=1;if(t.m.actual_risk_cash<=0)t.flags="INVALID_INITIAL_RISK";m_trades[i]=t;if(t.signal_index>=0)m_signals[t.signal_index].final_trade_status="FINALIZED";}}}
   int UnknownE2Positions(const string symbol)const{int n=0;for(int i=0;i<PositionsTotal();i++){ulong t=PositionGetTicket(i);if(t>0&&(ulong)PositionGetInteger(POSITION_MAGIC)==m_magic&&PositionGetString(POSITION_SYMBOL)==symbol&&FindPosition((ulong)PositionGetInteger(POSITION_IDENTIFIER))<0)n++;}return(n);}bool IsFinalizedPosition(const ulong id)const{int i=FindPosition(id);return(i>=0&&m_trades[i].finalized);}int RegisteredCount()const{return(ArraySize(m_trades));}int FinalizedCount()const{int n=0;for(int i=0;i<ArraySize(m_trades);i++)if(m_trades[i].finalized)n++;return(n);}int DuplicateExecutionIds()const{return(m_duplicates);}int DuplicateFinalizedTrades()const{return(m_duplicate_finals);}int CausalityViolations()const{return(m_causality);}bool CsvEnabled()const{return(m_csv_enabled);}
   // A validated recovered position legitimately has no pre-restart in-memory signal row.
   void Verify(const int total_candidates,const int requests,const int attempts,const int successes,const int new_registered){ZeroMemory(m_reconcile);ZeroMemory(m_financial);m_reconcile.signal_rows=ArraySize(m_signals);m_reconcile.total_candidates=total_candidates;m_reconcile.trade_requests=requests;m_reconcile.execution_attempts=attempts;m_reconcile.execution_successes=successes;m_reconcile.new_positions_registered=new_registered;m_reconcile.finalized_trades=FinalizedCount();for(int i=0;i<ArraySize(m_signals);i++){if(UniqueSignal(i))m_reconcile.unique_signal_candidate_ids++;else m_reconcile.duplicate_signal_rows++;string s=m_signals[i].status;if(s=="EXECUTED")m_reconcile.executed_candidates++;else if(s=="EXECUTION_FAILED")m_reconcile.execution_failed_candidates++;else if(s=="EXPIRED")m_reconcile.expired_candidates++;else if(s=="POSITION_REJECTED")m_reconcile.position_rejected_candidates++;else if(s=="DAY_REJECTED")m_reconcile.day_rejected_candidates++;else if(s=="SIZING_REJECTED")m_reconcile.sizing_rejected_candidates++;else if(s=="SAFETY_REJECTED")m_reconcile.safety_rejected_candidates++;else m_reconcile.other_candidate_outcomes++;}m_reconcile.candidate_outcome_sum=m_reconcile.executed_candidates+m_reconcile.execution_failed_candidates+m_reconcile.expired_candidates+m_reconcile.position_rejected_candidates+m_reconcile.day_rejected_candidates+m_reconcile.sizing_rejected_candidates+m_reconcile.safety_rejected_candidates+m_reconcile.other_candidate_outcomes;for(int i=0;i<ArraySize(m_trades);i++)if(m_trades[i].finalized){m_reconcile.trade_rows++;if(UniqueTrade(i))m_reconcile.unique_trade_ids++;else m_reconcile.duplicate_trade_rows++;if(m_trades[i].signal_index<0&&m_trades[i].recovery_count==0)m_reconcile.orphan_trade_rows++;m_financial.trades_checked++;m_financial.gross_profit_sum+=m_trades[i].gross;m_financial.commission_sum+=m_trades[i].commission;m_financial.swap_sum+=m_trades[i].swap;m_financial.fee_sum+=m_trades[i].fee;m_financial.net_profit_sum+=m_trades[i].net;m_financial.mt5_authoritative_profit_sum+=m_trades[i].gross+m_trades[i].commission+m_trades[i].swap+m_trades[i].fee;if(m_trades[i].m.actual_risk_cash<=0)m_financial.invalid_initial_risk_trades++;if(!MathIsValidNumber(m_trades[i].realized_r))m_financial.invalid_realized_r_trades++;}m_financial.financial_difference=m_financial.net_profit_sum-m_financial.mt5_authoritative_profit_sum;m_reconcile.missing_signal_rows=MathMax(0,total_candidates-m_reconcile.signal_rows);m_reconcile.missing_trade_rows=MathMax(0,m_reconcile.finalized_trades-m_reconcile.trade_rows);m_reconcile.write_failures=m_write_failures;m_reconcile.reconciliation_violations=m_reconcile.duplicate_signal_rows+m_reconcile.duplicate_trade_rows+m_reconcile.orphan_trade_rows+m_reconcile.missing_signal_rows+m_reconcile.missing_trade_rows+(m_reconcile.candidate_outcome_sum==total_candidates?0:1);}
   E2ReconcileVerification ReconcileVerification()const{return(m_reconcile);}E2FinancialVerification FinancialVerification()const{return(m_financial);}string RunId()const{return(m_run_id);}string ConfigHash()const{return(m_hash);}string Mode()const{return(m_mode);}string Period()const{return(PeriodText());}
   void Close(){Reconcile();Verify(ArraySize(m_signals),0,0,0,0);if(!m_csv_enabled)return;FolderCreate("E2\\Reports",FILE_COMMON);if(!ResolveReportPair())return;E2CsvExporter signals,trades;string h[],row[];if(!signals.Initialize(m_signal_file,*m_logger))m_write_failures++;else{SignalHeader(h);if(!signals.WriteHeader(h))m_write_failures++;for(int i=0;i<ArraySize(m_signals);i++){SignalRow(m_signals[i],row);if(!signals.WriteRow(row))m_write_failures++;}signals.Close();}if(!trades.Initialize(m_trade_file,*m_logger))m_write_failures++;else{TradeHeader(h);if(!trades.WriteHeader(h))m_write_failures++;for(int i=0;i<ArraySize(m_trades);i++)if(m_trades[i].finalized){TradeRow(m_trades[i],row);if(!trades.WriteRow(row))m_write_failures++;}trades.Close();}}
  };
#endif
