#ifndef E2_STRATEGY_E2ADXBBRECOVERY_MQH
#define E2_STRATEGY_E2ADXBBRECOVERY_MQH
#include "E2ADXBBTypes.mqh"
#include "..\\execution\\E2PositionGuard.mqh"

int E2ADXBBServerDay(const datetime value){MqlDateTime p;if(!TimeToStruct(value,p))return(0);return(p.year*10000+p.mon*100+p.day);}

class E2ADXBBRecovery
  {
private:
   ulong m_magic,m_active_position_id;string m_symbol,m_file;bool m_one_per_day;E2Logger *m_logger;E2ADXBBRecoveryVerification m_verify;E2ADXBBDayVerification m_day;E2ADXBBDayRecoveryDiagnostics m_day_diag;E2ADXBBRecoveryDiagnostics m_diag;
   string SafeSymbol()const{string s=m_symbol;StringReplace(s,".","_");StringReplace(s,"#","_");return(s);}
   string BrokerDate(const datetime value)const{string s=TimeToString(value,TIME_DATE);StringReplace(s,".","-");return(s);}
   void Fail(const string reason){m_diag.recovery_failure_reason=reason;m_verify.recovery_failures++;if(m_logger!=NULL)m_logger.Error("reason="+reason+", expected="+m_diag.state_file_expected+", found="+m_diag.state_file_found+".","Recovery");}
   bool OwnedPosition(ulong &identifier,ulong &ticket,E2TradeDirection &direction,double &entry,double &sl,double &tp,double &volume)const
     {identifier=0;ticket=0;direction=E2_DIRECTION_NONE;entry=0.0;sl=0.0;tp=0.0;volume=0.0;for(int i=0;i<PositionsTotal();i++){ulong t=PositionGetTicket(i);if(t>0&&PositionGetString(POSITION_SYMBOL)==m_symbol&&(ulong)PositionGetInteger(POSITION_MAGIC)==m_magic){ticket=t;identifier=(ulong)PositionGetInteger(POSITION_IDENTIFIER);direction=((ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE)==POSITION_TYPE_BUY?E2_DIRECTION_LONG:E2_DIRECTION_SHORT);entry=PositionGetDouble(POSITION_PRICE_OPEN);sl=PositionGetDouble(POSITION_SL);tp=PositionGetDouble(POSITION_TP);volume=PositionGetDouble(POSITION_VOLUME);return(true);}}return(false);}
   bool ExitDealExists(const ulong position_id)const{if(!HistorySelect(0,TimeCurrent()))return(false);for(int i=HistoryDealsTotal()-1;i>=0;i--){ulong d=HistoryDealGetTicket(i);if(d==0||(ulong)HistoryDealGetInteger(d,DEAL_POSITION_ID)!=position_id)continue;ENUM_DEAL_ENTRY e=(ENUM_DEAL_ENTRY)HistoryDealGetInteger(d,DEAL_ENTRY);if(e==DEAL_ENTRY_OUT||e==DEAL_ENTRY_OUT_BY)return(true);}return(false);}
   bool ReadField(const int h,string &value,int &fields){if(FileIsEnding(h))return(false);value=FileReadString(h);fields++;m_diag.fields_read=fields;return(true);}
   bool Parse(const int h,E2ADXBBPositionMetadata &m)
     {string f;int fields=0;ZeroMemory(m);if(!ReadField(h,f,fields)||f!="E2ADXBB2"){m_diag.recovery_failure_reason="STATE_SCHEMA_MISMATCH";return(false);}if(!ReadField(h,f,fields)||f!="ADXBB"){m_diag.recovery_failure_reason="STATE_SCHEMA_MISMATCH";return(false);}if(!ReadField(h,f,fields))return(false);ulong row_magic=(ulong)StringToInteger(f);m_diag.magic_match=(int)(row_magic==m_magic);if(!ReadField(h,m.candidate_id,fields)||!ReadField(h,m.execution_id,fields)||!ReadField(h,m.symbol,fields))return(false);if(!ReadField(h,f,fields))return(false);m.direction=(E2TradeDirection)StringToInteger(f);if(!ReadField(h,f,fields))return(false);m.signal_time=(datetime)StringToInteger(f);if(!ReadField(h,f,fields))return(false);m.entry_time=(datetime)StringToInteger(f);if(!ReadField(h,f,fields))return(false);m.entry_deal=(ulong)StringToInteger(f);if(!ReadField(h,f,fields))return(false);m.position_id=(ulong)StringToInteger(f);if(!ReadField(h,f,fields))return(false);m.position_ticket=(ulong)StringToInteger(f);if(!ReadField(h,f,fields))return(false);m.volume=StringToDouble(f);if(!ReadField(h,f,fields))return(false);m.fill_price=StringToDouble(f);if(!ReadField(h,f,fields))return(false);m.submitted_stop=StringToDouble(f);if(!ReadField(h,f,fields))return(false);m.original_r=StringToDouble(f);if(!ReadField(h,f,fields))return(false);m.target_r=StringToDouble(f);if(!ReadField(h,f,fields))return(false);m.target_price=StringToDouble(f);if(!ReadField(h,f,fields))return(false);m.requested_risk_cash=StringToDouble(f);if(!ReadField(h,f,fields))return(false);m.actual_risk_cash=StringToDouble(f);m_diag.rows_read=1;if(fields!=20){m_diag.recovery_failure_reason="STATE_ROW_PARSE_FAILED";return(false);}m_diag.valid_rows_parsed=1;return(true);}
public:
   E2ADXBBRecovery(void):m_magic(0),m_active_position_id(0),m_symbol(""),m_file(""),m_one_per_day(false),m_logger(NULL){ZeroMemory(m_verify);ZeroMemory(m_day);ZeroMemory(m_day_diag);ZeroMemory(m_diag);}
   bool Initialize(const E2Config &c,const string symbol,E2Logger &logger,E2ADXBBPositionMetadata &recovered,bool &has_recovered)
     {m_magic=c.expert_magic_number;m_symbol=symbol;m_one_per_day=c.one_trade_per_day;m_logger=&logger;m_active_position_id=0;ZeroMemory(m_verify);ZeroMemory(m_day);ZeroMemory(m_day_diag);ZeroMemory(m_diag);m_day.enabled=(int)m_one_per_day;m_file="E2_ADXBB_STATE_"+StringFormat("%I64u",m_magic)+"_"+SafeSymbol()+".csv";m_diag.state_file_expected=TerminalInfoString(TERMINAL_COMMONDATA_PATH)+"\\Files\\"+m_file;ZeroMemory(recovered);has_recovered=false;
      ulong live_id=0,live_ticket=0;E2TradeDirection live_direction=E2_DIRECTION_NONE;double live_entry=0.0,live_sl=0.0,live_tp=0.0,live_volume=0.0;const bool open=OwnedPosition(live_id,live_ticket,live_direction,live_entry,live_sl,live_tp,live_volume);if(open)m_verify.startup_open_positions++;
      if(!FileIsExist(m_file,FILE_COMMON)){if(open)Fail("STATE_FILE_NOT_FOUND");return(!open);}m_diag.state_file_found=m_diag.state_file_expected;ResetLastError();int h=FileOpen(m_file,FILE_READ|FILE_CSV|FILE_ANSI|FILE_COMMON,';');m_diag.file_open_error=GetLastError();if(h==INVALID_HANDLE){Fail("STATE_FILE_OPEN_FAILED");return(false);}m_diag.file_open_success=1;m_diag.rows_read=1;m_diag.expected_fields=20;bool parsed=Parse(h,recovered);FileClose(h);if(!parsed){if(m_diag.recovery_failure_reason=="")m_diag.recovery_failure_reason="STATE_ROW_PARSE_FAILED";Fail(m_diag.recovery_failure_reason);return(false);}
      m_diag.symbol_match=(int)(recovered.symbol==m_symbol);m_diag.position_identifier_match=(int)(open&&recovered.position_id==live_id);m_diag.position_ticket_match=(int)(open&&recovered.position_ticket==live_ticket);m_diag.direction_match=(int)(open&&recovered.direction==live_direction);m_diag.entry_deal_resolved=(int)(recovered.entry_deal>0&&HistoryDealSelect(recovered.entry_deal));m_diag.fill_valid=(int)(recovered.fill_price>0.0&&MathIsValidNumber(recovered.fill_price));m_diag.initial_sl_valid=(int)(recovered.submitted_stop>0.0&&MathIsValidNumber(recovered.submitted_stop));m_diag.original_r_valid=(int)(recovered.original_r>0.0&&MathIsValidNumber(recovered.original_r));m_diag.target_r_valid=(int)(recovered.target_r>0.0&&MathIsValidNumber(recovered.target_r));m_diag.tp_valid=(int)(recovered.target_price>0.0&&MathIsValidNumber(recovered.target_price));
      if(!open){if(ExitDealExists(recovered.position_id)){FileDelete(m_file,FILE_COMMON);m_verify.states_cleared++;return(true);}m_verify.orphan_states++;Fail("NO_MATCHING_POSITION_RECORD");return(false);}E2SymbolSpecification spec;double tick=SymbolInfoDouble(m_symbol,SYMBOL_TRADE_TICK_SIZE);double tol=MathMax(1e-10,tick*1e-6);
      if(!m_diag.magic_match){Fail("MAGIC_MISMATCH");return(false);}if(!m_diag.symbol_match){Fail("SYMBOL_MISMATCH");return(false);}if(!m_diag.position_identifier_match){Fail("POSITION_ID_MISMATCH");return(false);}if(!m_diag.direction_match){Fail("DIRECTION_MISMATCH");return(false);}if(!m_diag.entry_deal_resolved){Fail("ENTRY_DEAL_NOT_FOUND");return(false);}if(!m_diag.fill_valid||MathAbs(recovered.fill_price-live_entry)>tol){Fail("INVALID_FILL");return(false);}m_diag.sl_comparisons_performed++;if(!m_diag.initial_sl_valid||MathAbs(recovered.submitted_stop-live_sl)>tol){m_diag.sl_mismatches++;Fail("INVALID_INITIAL_SL");return(false);}m_diag.original_r_comparisons_performed++;if(!m_diag.original_r_valid||MathAbs(recovered.original_r-MathAbs(recovered.fill_price-recovered.submitted_stop))>tol){m_diag.original_r_mismatches++;Fail("INVALID_ORIGINAL_R");return(false);}if(!m_diag.target_r_valid){Fail("INVALID_TARGET_R");return(false);}m_diag.tp_comparisons_performed++;if(!m_diag.tp_valid||MathAbs(recovered.target_price-live_tp)>tol){m_diag.tp_mismatches++;Fail("INVALID_TP");return(false);}if(recovered.volume<=0.0||MathAbs(recovered.volume-live_volume)>1e-10){Fail("OTHER");return(false);}
      has_recovered=true;m_active_position_id=recovered.position_id;m_verify.states_loaded++;m_diag.selected_recovery_record=recovered.execution_id;m_diag.recovery_failure_reason="NONE";return(true);}
   bool Save(const E2ADXBBPositionMetadata &m)
     {ResetLastError();int h=FileOpen(m_file,FILE_WRITE|FILE_CSV|FILE_ANSI|FILE_COMMON,';');if(h==INVALID_HANDLE){Fail("STATE_FILE_OPEN_FAILED");return(false);}uint written=FileWrite(h,"E2ADXBB2","ADXBB",StringFormat("%I64u",m_magic),m.candidate_id,m.execution_id,m.symbol,IntegerToString((int)m.direction),IntegerToString((long)m.signal_time),IntegerToString((long)m.entry_time),StringFormat("%I64u",m.entry_deal),StringFormat("%I64u",m.position_id),StringFormat("%I64u",m.position_ticket),DoubleToString(m.volume,8),DoubleToString(m.fill_price,16),DoubleToString(m.submitted_stop,16),DoubleToString(m.original_r,16),DoubleToString(m.target_r,16),DoubleToString(m.target_price,16),DoubleToString(m.requested_risk_cash,8),DoubleToString(m.actual_risk_cash,8));FileFlush(h);FileClose(h);if(written==0){Fail("STATE_ROW_PARSE_FAILED");return(false);}m_active_position_id=m.position_id;m_verify.states_saved++;return(true);}
   void Reconcile(const bool finalized){if(finalized&&m_active_position_id>0&&FileIsExist(m_file,FILE_COMMON)){if(FileDelete(m_file,FILE_COMMON)){m_verify.states_cleared++;m_active_position_id=0;}}}
   bool ScanDayLock(const datetime target_time,const ulong target_deal,const bool recovery_scan)
     {if(!m_one_per_day)return(false);datetime authoritative_target=target_time;if(recovery_scan){ZeroMemory(m_day_diag);m_day_diag.current_server_time=TimeCurrent();m_day_diag.current_server_date=BrokerDate(m_day_diag.current_server_time);m_day_diag.recovered_position_entry_deal=target_deal;if(target_deal==0||!HistoryDealSelect(target_deal)){m_day_diag.failure_reason="RECOVERED_ENTRY_DEAL_NOT_FOUND";m_day.daily_lock_failure_reason=m_day_diag.failure_reason;return(false);}authoritative_target=(datetime)HistoryDealGetInteger(target_deal,DEAL_TIME);m_day_diag.recovered_position_entry_time=authoritative_target;m_day_diag.recovered_position_entry_date=BrokerDate(authoritative_target);m_day_diag.target_broker_date=m_day_diag.recovered_position_entry_date;}
      const int wanted=E2ADXBBServerDay(authoritative_target);m_day.history_range_start=0;m_day.history_range_end=MathMax(TimeCurrent(),authoritative_target)+1;int scanned=0,owned=0,same=0;if(!HistorySelect(m_day.history_range_start,m_day.history_range_end)){m_day.daily_lock_failure_reason="HISTORY_SELECT_FAILED";if(recovery_scan)m_day_diag.failure_reason=m_day.daily_lock_failure_reason;return(false);}for(int i=HistoryDealsTotal()-1;i>=0;i--){ulong d=HistoryDealGetTicket(i);if(d==0)continue;scanned++;ulong magic=(ulong)HistoryDealGetInteger(d,DEAL_MAGIC);string symbol=HistoryDealGetString(d,DEAL_SYMBOL);ENUM_DEAL_ENTRY entry=(ENUM_DEAL_ENTRY)HistoryDealGetInteger(d,DEAL_ENTRY);string comment=HistoryDealGetString(d,DEAL_COMMENT);if(magic!=m_magic||symbol!=m_symbol||entry!=DEAL_ENTRY_IN||StringFind(comment,"E2ADXBB|")!=0)continue;owned++;datetime deal_time=(datetime)HistoryDealGetInteger(d,DEAL_TIME);int deal_day=E2ADXBBServerDay(deal_time);bool match=(deal_day==wanted);if(match)same++;if(recovery_scan&&(m_day_diag.latest_owned_entry_deal==0||deal_time>m_day_diag.latest_owned_entry_deal_time)){m_day_diag.latest_owned_entry_deal=d;m_day_diag.latest_owned_entry_deal_time=deal_time;m_day_diag.latest_owned_entry_deal_date=BrokerDate(deal_time);}}
      m_day.entry_deals_scanned=scanned;m_day.owned_entry_deals_found=MathMax(m_day.owned_entry_deals_found,owned);m_day.today_owned_entry_deals_found=MathMax(m_day.today_owned_entry_deals_found,same);if(recovery_scan){m_day_diag.owned_entry_deals_found=owned;m_day_diag.same_date_owned_entry_deals_found=same;m_day_diag.date_comparison_result=(same>0?"MATCH":"NO_MATCH");m_day_diag.failure_reason=(same>0?"NONE":"NO_OWNED_ENTRY_DEAL_FOR_DAY");}
      if(same>0){m_day.history_locks_found++;m_day.daily_lock_recovered=1;m_day.daily_lock_failure_reason="NONE";return(true);}if(m_day.daily_lock_recovered==0)m_day.daily_lock_failure_reason="NO_OWNED_ENTRY_DEAL_FOR_DAY";return(false);}
   bool DayConsumed(const datetime time){return(ScanDayLock(time,0,false));}
   bool ReconstructDayLock(const ulong entry_deal,const datetime fallback_time){return(ScanDayLock(fallback_time,entry_deal,true));}
   void RecordLock(){if(m_one_per_day)m_day.locks_created++;}void RecordSuppressed(){m_day.candidates_suppressed++;}
   bool StateFileExists()const{return(FileIsExist(m_file,FILE_COMMON));}ulong ActivePositionId()const{return(m_active_position_id);}E2ADXBBRecoveryVerification Verification()const{return(m_verify);}E2ADXBBDayVerification DayVerification()const{return(m_day);}E2ADXBBDayRecoveryDiagnostics DayRecoveryDiagnostics()const{return(m_day_diag);}E2ADXBBRecoveryDiagnostics Diagnostics()const{return(m_diag);}
  };
#endif
