#ifndef E2_STRATEGY_E2OBRTRADEPLANNER_MQH
#define E2_STRATEGY_E2OBRTRADEPLANNER_MQH
#include "E2OBRTypes.mqh"
#include "E2OBRRecovery.mqh"
#include "..\\risk\\E2PositionSizer.mqh"
#include "..\\risk\\E2OrderRequest.mqh"
#include "..\\execution\\E2PositionGuard.mqh"
#include "..\\execution\\E2OrderExecutor.mqh"
#include "..\\reporting\\E2CsvExporter.mqh"
class E2OBRTradePlanner
  {
private:
 E2Config m_config;string m_symbol,m_request_ids[],m_execution_ids[];E2SymbolInfo *m_symbol_info;E2PositionSizer *m_sizer;E2PositionGuard *m_guard;E2OBRRecovery *m_recovery;E2Logger *m_logger;E2OBRPlanVerification m_plan;E2OBRExecutionVerification m_exec;E2OBREntryTimeVerification m_time;E2OBREntryGapVerification m_gap;E2CsvExporter m_audit;long m_audit_rows;E2OBRCandidate m_last_candidate;E2OBRPlanContext m_last_context;
 bool Seen(const string &v[],const string id)const{for(int i=0;i<ArraySize(v);i++)if(v[i]==id)return(true);return(false);}void Remember(string &v[],const string id){int n=ArraySize(v);ArrayResize(v,n+1);v[n]=id;}double ND(const double v,const E2SymbolSpecification &s)const{return(NormalizeDouble(MathFloor(v/s.tick_size+1e-10)*s.tick_size,s.digits));}double NU(const double v,const E2SymbolSpecification &s)const{return(NormalizeDouble(MathCeil(v/s.tick_size-1e-10)*s.tick_size,s.digits));}string T(datetime v)const{return(v>0?TimeToString(v,TIME_DATE|TIME_SECONDS):"");}string D(const string day)const{if(StringLen(day)!=8)return("INVALID");datetime v=StringToTime(StringSubstr(day,0,4)+"."+StringSubstr(day,4,2)+"."+StringSubstr(day,6,2));MqlDateTime p;TimeToStruct(v,p);string n[]={"SUN","MON","TUE","WED","THU","FRI","SAT"};return(n[p.day_of_week]);}
 void Audit(const E2OBRCandidate &c,const E2OBRPlanContext &x,string decision,string reason){if(!m_audit.IsInitialized())return;double b=(c.direction==E2_DIRECTION_LONG?c.or_high:c.or_low),d=(x.quote_price>0?(c.direction==E2_DIRECTION_LONG?x.quote_price-c.or_high:c.or_low-x.quote_price):0);string row[]={c.candidate_id,c.symbol,c.london_day,D(c.london_day),E2TradeDirectionName(c.direction),T(c.breakout_candle_time),T(c.candidate_known_from),decision,reason,DoubleToString(b,8),DoubleToString(c.atr,8),DoubleToString(m_config.obr_maximum_breakout_gap_atr*c.atr,8),DoubleToString(x.quote_price,8),DoubleToString(d,8),DoubleToString(c.atr>0?d/c.atr:0,8),DoubleToString(c.or_high,8),DoubleToString(c.or_low,8),DoubleToString(c.breakout_close,8),DoubleToString(c.adx,6),DoubleToString(c.or_size_atr_ratio,8),DoubleToString(c.breakout_distance_atr_ratio,8)};if(m_audit.WriteRow(row))m_audit_rows++;}
public:
 E2OBRTradePlanner(void):m_symbol(""),m_symbol_info(NULL),m_sizer(NULL),m_guard(NULL),m_recovery(NULL),m_logger(NULL),m_audit_rows(0){ZeroMemory(m_plan);ZeroMemory(m_exec);ZeroMemory(m_time);ZeroMemory(m_gap);}
 void Initialize(string symbol,const E2Config &config,E2SymbolInfo &si,E2PositionSizer &sizer,E2PositionGuard &guard,E2OBRRecovery &recovery,E2Logger &logger){m_symbol=symbol;m_config=config;m_symbol_info=&si;m_sizer=&sizer;m_guard=&guard;m_recovery=&recovery;m_logger=&logger;ArrayResize(m_request_ids,0);ArrayResize(m_execution_ids,0);ZeroMemory(m_plan);ZeroMemory(m_exec);ZeroMemory(m_time);ZeroMemory(m_gap);m_audit_rows=0;if(config.csv_export_enabled&&m_audit.Initialize("E2_OBR_decisions_"+symbol+"_"+IntegerToString((int)TimeCurrent())+".csv",logger)){string h[]={"candidate_id","symbol","london_day","london_weekday","direction","breakout_timestamp","intended_entry_timestamp","decision","rejection_reason","or_boundary","frozen_atr","maximum_allowed_distance","executable_entry_quote","actual_distance","distance_atr","or_high","or_low","breakout_close","adx","or_atr","breakout_gap_atr"};m_audit.WriteHeader(h);}}
 bool Build(const E2OBRCandidate &c,E2OrderRequest &r,E2OBRPlanContext &x){E2ResetOrderRequest(r);ZeroMemory(x);x.candidate=c;m_plan.candidates_received++;m_time.candidates_checked++;datetime intended=c.candidate_known_from,current=iTime(c.symbol,PERIOD_M15,0),now=TimeCurrent();x.intended_entry_time=intended;if(intended<=0)m_time.missing_candidate_timestamp++;
  if(current!=intended||now<intended||now>=intended+PeriodSeconds(PERIOD_M15)){m_plan.expired_candidates++;m_time.missed_window_candidates++;Audit(c,x,"REJECT","MISSED_WINDOW");return(false);}m_plan.entry_windows_reached++;if(c.candidate_known_from<=c.breakout_candle_time||intended!=c.breakout_candle_time+PeriodSeconds(PERIOD_M15)){m_plan.plan_causality_violations++;Audit(c,x,"REJECT","OTHER");return(false);}if(m_recovery!=NULL&&m_recovery.DayConsumed(c.london_day)){m_plan.rejected_day_consumed++;Audit(c,x,"REJECT","DAY_CONSUMED");return(false);}r.execution_id=c.candidate_id+"_ENTRY";if(Seen(m_request_ids,r.execution_id)){m_plan.duplicate_requests++;Audit(c,x,"REJECT","OTHER");return(false);}Remember(m_request_ids,r.execution_id);if(m_guard==NULL||m_guard.HasOpenE2Position(c.symbol)||m_guard.HasPendingE2Order(c.symbol)){m_plan.rejected_position_open++;Audit(c,x,"REJECT","POSITION_OPEN");return(false);}
  if(m_symbol_info==NULL||!m_symbol_info.Refresh(c.symbol)){m_plan.rejected_other++;Audit(c,x,"REJECT","OTHER");return(false);}E2SymbolSpecification s=m_symbol_info.Specification();MqlTick tick;if(!SymbolInfoTick(c.symbol,tick)||tick.bid<=0||tick.ask<=0||tick.ask<tick.bid||tick.time<=0||(m_config.max_quote_age_seconds>0&&now-tick.time>m_config.max_quote_age_seconds)){m_plan.rejected_quote++;Audit(c,x,"REJECT","QUOTE");return(false);}double entry=(c.direction==E2_DIRECTION_LONG?tick.ask:tick.bid);x.quote_price=entry;x.request_time=(datetime)tick.time;double gap=(c.direction==E2_DIRECTION_LONG?entry-c.or_high:c.or_low-entry),limit=m_config.obr_maximum_breakout_gap_atr*c.atr;if(gap>limit){m_plan.rejected_entry_gap++;m_gap.rejected_checked++;Audit(c,x,"REJECT","ENTRY_GAP");return(false);}m_gap.accepted_checked++;
  double structural=(c.direction==E2_DIRECTION_LONG?c.or_low-m_config.obr_stop_buffer_atr*c.atr:c.or_high+m_config.obr_stop_buffer_atr*c.atr);x.structural_stop=structural;if((c.direction==E2_DIRECTION_LONG&&structural>=entry)||(c.direction==E2_DIRECTION_SHORT&&structural<=entry)){m_plan.rejected_stop_geometry++;Audit(c,x,"REJECT","STOP_GEOMETRY");return(false);}double minimum=MathMax((double)SymbolInfoInteger(c.symbol,SYMBOL_TRADE_STOPS_LEVEL),(double)SymbolInfoInteger(c.symbol,SYMBOL_TRADE_FREEZE_LEVEL))*s.point,submitted=structural;if(c.direction==E2_DIRECTION_LONG){if(minimum>0)submitted=MathMin(submitted,entry-minimum);submitted=ND(submitted,s);}else{if(minimum>0)submitted=MathMax(submitted,entry+minimum);submitted=NU(submitted,s);}x.submitted_stop=submitted;if(submitted<=0||(c.direction==E2_DIRECTION_LONG&&submitted>=entry)||(c.direction==E2_DIRECTION_SHORT&&submitted<=entry)){m_plan.rejected_stop_geometry++;Audit(c,x,"REJECT","STOP_GEOMETRY");return(false);}
  E2PositionSizingResult z;if(m_sizer==NULL||!m_sizer.CalculateRequestedRisk(c.symbol,c.direction,entry,submitted,z,true)){m_plan.rejected_sizing++;Audit(c,x,"REJECT","SIZING");return(false);}x.requested_risk_cash=z.target_risk_money;x.planned_risk_cash=z.actual_risk_money;x.volume=z.volume;x.request_time=now;r.status=E2_ORDER_REQUEST_VALID;r.symbol=c.symbol;r.setup_id="OBR";r.signal_id=c.candidate_id;r.direction=c.direction;r.signal_time=c.breakout_candle_time;r.signal_known_from=c.candidate_known_from;r.request_time=now;r.requested_entry_price=entry;r.structural_stop_price=structural;r.submitted_stop_price=submitted;r.take_profit_price=0;r.requested_risk_cash=z.target_risk_money;r.volume=z.volume;m_plan.valid_execution_requests++;if(c.direction==E2_DIRECTION_LONG)m_plan.long_requests++;else m_plan.short_requests++;m_last_candidate=c;m_last_context=x;Audit(c,x,"REQUEST","NONE");return(true);}
 bool BeginExecution(const E2OrderRequest &r){m_exec.requests_received++;m_time.attempts_checked++;datetime bar=iTime(r.symbol,PERIOD_M15,0);if(r.signal_known_from<=0)m_time.missing_candidate_timestamp++;else if(bar==r.signal_time)m_time.same_bar_violations++;else if(bar>r.signal_known_from)m_time.actual_late_execution_violations++;else if(bar<r.signal_known_from)m_time.early_entry_violations++;else m_time.correct_next_bar_attempts++;if(bar!=r.signal_known_from)m_time.entry_time_violations++;if(Seen(m_execution_ids,r.execution_id)){m_exec.duplicate_execution_attempts++;return(false);}Remember(m_execution_ids,r.execution_id);m_exec.execution_attempts++;if(r.direction==E2_DIRECTION_LONG)m_exec.long_attempts++;else m_exec.short_attempts++;return(true);}
 void RecordFailure(E2ExecutionStatus s){m_exec.execution_failures++;Audit(m_last_candidate,m_last_context,"REJECT","EXECUTION_FAILURE");if(s==E2_EXECUTION_SPREAD_TOO_HIGH)m_plan.rejected_spread++;else if(s==E2_EXECUTION_NO_VALID_QUOTE||s==E2_EXECUTION_MARKET_PRICE_UNAVAILABLE||s==E2_EXECUTION_PRICE_DEVIATION_EXCEEDED)m_plan.rejected_quote++;else if(s==E2_EXECUTION_MARGIN_INSUFFICIENT||s==E2_EXECUTION_INSUFFICIENT_MARGIN)m_plan.rejected_margin++;else if(s==E2_EXECUTION_POSITION_ALREADY_OPEN||s==E2_EXECUTION_PENDING_ORDER_EXISTS||s==E2_EXECUTION_DIRECTION_CONFLICT)m_plan.rejected_position_open++;else m_plan.rejected_other++;}
 void RecordSuccess(string day){m_exec.execution_successes++;m_exec.successful_entries++;m_exec.day_locks_created++;if(m_recovery!=NULL)m_recovery.RecordSuccessfulEntry(day);}void RecordUnresolved(void){m_exec.unresolved_execution_states++;}void RecordRegistrationFailure(void){m_exec.registration_failures++;}void RecordProtectionFailure(void){m_exec.protection_failures++;}
 void AuditWeekdaySuppression(const E2OBRSuppressedSignal &s){if(!m_audit.IsInitialized())return;double boundary=(s.direction==E2_DIRECTION_LONG?s.or_high:s.or_low),distance=s.gap_atr*s.atr;string row[]={"",s.symbol,s.london_day,s.london_weekday,E2TradeDirectionName(s.direction),T(s.breakout_time),"","SUPPRESS","DISABLED_WEEKDAY",DoubleToString(boundary,8),DoubleToString(s.atr,8),DoubleToString(m_config.obr_maximum_breakout_gap_atr*s.atr,8),"",DoubleToString(distance,8),DoubleToString(s.gap_atr,8),DoubleToString(s.or_high,8),DoubleToString(s.or_low,8),DoubleToString(s.breakout_close,8),DoubleToString(s.adx,6),DoubleToString(s.or_atr,8),DoubleToString(s.gap_atr,8)};if(m_audit.WriteRow(row))m_audit_rows++;}E2OBRPlanVerification PlanVerification(void)const{return(m_plan);}E2OBRExecutionVerification ExecutionVerification(void)const{return(m_exec);}E2OBREntryTimeVerification EntryTimeVerification(void)const{return(m_time);}E2OBREntryGapVerification EntryGapVerification(void)const{return(m_gap);}long AuditRows(void)const{return(m_audit_rows);}void CloseAudit(void){m_audit.Close();}
  };
#endif
