#ifndef E2_STRATEGY_E2STRATEGYANALYZER_MQH
#define E2_STRATEGY_E2STRATEGYANALYZER_MQH
#include "..\\analysis\\E2TrendAnalyzer.mqh"
#include "..\\analysis\\E2ZoneAnalyzer.mqh"
#include "..\\analysis\\E2ConfirmationAnalyzer.mqh"

enum E2StrategySignal { E2_SIGNAL_NONE,E2_SIGNAL_LONG,E2_SIGNAL_SHORT };
enum E2StrategyReason { E2_STRATEGY_VALID_LONG,E2_STRATEGY_VALID_SHORT,E2_STRATEGY_TREND_NOT_READY,E2_STRATEGY_TREND_RANGE,E2_STRATEGY_TREND_UNKNOWN,E2_STRATEGY_ZONES_NOT_READY,E2_STRATEGY_NO_ACTIONABLE_SUPPORT,E2_STRATEGY_NO_ACTIONABLE_RESISTANCE,E2_STRATEGY_CONFIRMATION_NOT_READY,E2_STRATEGY_NO_CONFIRMATION,E2_STRATEGY_CONFIRMATION_CONFLICT,E2_STRATEGY_CONFIRMATION_DIRECTION_MISMATCH,E2_STRATEGY_NO_ZONE_INTERACTION };
struct E2StrategyResult { datetime evaluation_time,trend_closed_h4_time,zone_interaction_time,confirmation_candle_time; E2StrategySignal signal; E2StrategyReason reason; E2TrendState trend_state; double adx_value; int selected_zone_id; E2ZoneType selected_zone_role; E2ZoneState selected_zone_state; double selected_zone_lower,selected_zone_upper,selected_zone_center; bool zone_interaction,ready,confirmation_conflict; E2ConfirmationDirection confirmation_direction,engulfing,pin_bar,momentum,previous_break; };
string E2StrategySignalName(E2StrategySignal s){return(s==E2_SIGNAL_LONG?"LONG":(s==E2_SIGNAL_SHORT?"SHORT":"NONE"));}
string E2StrategyReasonName(E2StrategyReason r){switch(r){case E2_STRATEGY_VALID_LONG:return("VALID_LONG");case E2_STRATEGY_VALID_SHORT:return("VALID_SHORT");case E2_STRATEGY_TREND_NOT_READY:return("TREND_NOT_READY");case E2_STRATEGY_TREND_RANGE:return("TREND_RANGE");case E2_STRATEGY_TREND_UNKNOWN:return("TREND_UNKNOWN");case E2_STRATEGY_ZONES_NOT_READY:return("ZONES_NOT_READY");case E2_STRATEGY_NO_ACTIONABLE_SUPPORT:return("NO_ACTIONABLE_SUPPORT");case E2_STRATEGY_NO_ACTIONABLE_RESISTANCE:return("NO_ACTIONABLE_RESISTANCE");case E2_STRATEGY_CONFIRMATION_NOT_READY:return("CONFIRMATION_NOT_READY");case E2_STRATEGY_NO_CONFIRMATION:return("NO_CONFIRMATION");case E2_STRATEGY_CONFIRMATION_CONFLICT:return("CONFIRMATION_CONFLICT");case E2_STRATEGY_CONFIRMATION_DIRECTION_MISMATCH:return("CONFIRMATION_DIRECTION_MISMATCH");default:return("NO_ZONE_INTERACTION");}}
class E2StrategyAnalyzer
 {private:E2TrendAnalyzer *m_trend;E2ZoneAnalyzer *m_zones;E2ConfirmationAnalyzer *m_confirmation;E2MarketData *m_market;
 void Reset(E2StrategyResult &r,const datetime t)const{ZeroMemory(r);r.evaluation_time=t;r.signal=E2_SIGNAL_NONE;r.reason=E2_STRATEGY_TREND_NOT_READY;r.trend_state=E2_TREND_UNKNOWN;r.selected_zone_id=-1;r.selected_zone_role=E2_ZONE_SUPPORT;r.selected_zone_state=E2_ZONE_CANDIDATE;r.confirmation_direction=E2_CONFIRMATION_NONE;}
 bool Better(const E2Zone &a,const E2Zone &b,const double close)const{int ar=(a.state==E2_ZONE_ROLE_REVERSED_ACTIVE?1:0),br=(b.state==E2_ZONE_ROLE_REVERSED_ACTIVE?1:0);if(ar!=br)return(ar>br);if(a.touches!=b.touches)return(a.touches>b.touches);if(a.last_touch_time!=b.last_touch_time)return(a.last_touch_time>b.last_touch_time);double da=MathAbs(close-a.center),db=MathAbs(close-b.center);if(da!=db)return(da<db);return(a.id<b.id);}
 void Select(const E2Zone &z,E2StrategyResult &r)const{r.selected_zone_id=z.id;r.selected_zone_role=z.type;r.selected_zone_state=z.state;r.selected_zone_lower=z.lower;r.selected_zone_upper=z.upper;r.selected_zone_center=z.center;r.zone_interaction=true;r.zone_interaction_time=r.confirmation_candle_time;}
 public:E2StrategyAnalyzer(void):m_trend(NULL),m_zones(NULL),m_confirmation(NULL),m_market(NULL){}
 void Initialize(E2TrendAnalyzer &trend,E2ZoneAnalyzer &zones,E2ConfirmationAnalyzer &confirmation,E2MarketData &market){m_trend=&trend;m_zones=&zones;m_confirmation=&confirmation;m_market=&market;}
 bool Evaluate(const string symbol,const datetime evaluation,E2StrategyResult &r){Reset(r,evaluation);if(m_trend==NULL||m_zones==NULL||m_confirmation==NULL||m_market==NULL)return(false);E2TrendResult trend;if(!m_trend.Evaluate(symbol,evaluation,trend)){r.reason=E2_STRATEGY_TREND_NOT_READY;return(false);}r.trend_state=trend.state;r.trend_closed_h4_time=trend.closed_bar_time;r.adx_value=trend.adx_value;if(trend.state==E2_TREND_UNKNOWN){r.reason=E2_STRATEGY_TREND_UNKNOWN;return(true);}if(trend.state==E2_TREND_RANGE){r.reason=E2_STRATEGY_TREND_RANGE;return(true);}E2ConfirmationResult confirmation;if(!m_confirmation.Evaluate(symbol,evaluation,confirmation)||confirmation.readiness==E2_CONFIRMATION_NOT_READY||confirmation.readiness==E2_CONFIRMATION_DATA_ERROR){r.reason=E2_STRATEGY_CONFIRMATION_NOT_READY;return(false);}r.confirmation_direction=confirmation.direction;r.confirmation_candle_time=confirmation.candle_time;r.confirmation_conflict=confirmation.directional_conflict;r.engulfing=confirmation.engulfing;r.pin_bar=confirmation.pin_bar;r.momentum=confirmation.momentum;r.previous_break=confirmation.previous_break;if(confirmation.directional_conflict){r.reason=E2_STRATEGY_CONFIRMATION_CONFLICT;return(true);}if(confirmation.direction==E2_CONFIRMATION_NONE){r.reason=E2_STRATEGY_NO_CONFIRMATION;return(true);}if((trend.state==E2_TREND_BULLISH&&confirmation.direction!=E2_CONFIRMATION_BULLISH)||(trend.state==E2_TREND_BEARISH&&confirmation.direction!=E2_CONFIRMATION_BEARISH)){r.reason=E2_STRATEGY_CONFIRMATION_DIRECTION_MISMATCH;return(true);}E2Zone zones[];int candidates=0;if(!m_zones.Evaluate(symbol,evaluation,zones,candidates)){r.reason=E2_STRATEGY_ZONES_NOT_READY;return(false);}MqlRates candle;if(!m_market.GetClosedBarAsOf(symbol,m_market.ConfirmationTimeframe(),evaluation,candle)){r.reason=E2_STRATEGY_CONFIRMATION_NOT_READY;return(false);}E2ZoneType desired=(trend.state==E2_TREND_BULLISH?E2_ZONE_SUPPORT:E2_ZONE_RESISTANCE);int best=-1,actionable=0;for(int i=0;i<ArraySize(zones);i++)if(zones[i].actionable&&zones[i].type==desired){actionable++;if(candle.low<=zones[i].upper&&candle.high>=zones[i].lower){if(best<0||Better(zones[i],zones[best],candle.close))best=i;}}if(actionable==0){r.reason=(desired==E2_ZONE_SUPPORT?E2_STRATEGY_NO_ACTIONABLE_SUPPORT:E2_STRATEGY_NO_ACTIONABLE_RESISTANCE);return(true);}if(best<0){r.reason=E2_STRATEGY_NO_ZONE_INTERACTION;return(true);}Select(zones[best],r);r.ready=true;if(desired==E2_ZONE_SUPPORT){r.signal=E2_SIGNAL_LONG;r.reason=E2_STRATEGY_VALID_LONG;}else{r.signal=E2_SIGNAL_SHORT;r.reason=E2_STRATEGY_VALID_SHORT;}return(true);} };
#endif
