#ifndef E2_STRATEGY_E2V2TRADEPLANENGINE_MQH
#define E2_STRATEGY_E2V2TRADEPLANENGINE_MQH

#include "..\analysis\E2TrendContinuationEngine.mqh"
#include "..\analysis\E2RangeMeanReversionEngine.mqh"
#include "..\filters\E2SessionFilter.mqh"
#include "..\filters\E2NewsFilter.mqh"
#include "..\risk\E2PositionSizer.mqh"
#include "..\execution\E2PositionGuard.mqh"

enum E2V2ManagementBranch { E2_V2_MANAGEMENT_NONE,E2_V2_MANAGEMENT_FIXED_2R,E2_V2_MANAGEMENT_ZONE_TARGET_TRAILING };
enum E2V2PlanReason
  {
   E2_V2_PLAN_TREND_TOGGLE_DISABLED,E2_V2_PLAN_H4_REGIME_MISMATCH,E2_V2_PLAN_H4_TREND_INELIGIBLE,
   E2_V2_PLAN_H4_OVEREXTENDED,E2_V2_PLAN_ENTRY_ZONE_INVALID,E2_V2_PLAN_CANDIDATE_INVALID,
   E2_V2_PLAN_NOT_ENTRY_M15_OPEN,E2_V2_PLAN_SESSION_BLOCKED,E2_V2_PLAN_NEWS_BLOCKED,
   E2_V2_PLAN_POSITION_ALREADY_OPEN,E2_V2_PLAN_NO_OPPOSING_ZONE,E2_V2_PLAN_TARGET_ZONE_NOT_CAUSAL,
   E2_V2_PLAN_TARGET_SPACE_BELOW_2R,E2_V2_PLAN_INVALID_STOP,E2_V2_PLAN_INVALID_MANAGEMENT_CONFIGURATION,
   E2_V2_PLAN_RISK_SIZING_FAILED,E2_V2_PLAN_VOLUME_INVALID,E2_V2_PLAN_QUOTE_INVALID,
   E2_V2_PLAN_EXECUTION_SAFETY_FAILED,E2_V2_PLAN_DUPLICATE,E2_V2_PLAN_VALID
  };

string E2V2PlanReasonName(const E2V2PlanReason value)
  {
   string names[]={"TREND_TOGGLE_DISABLED","H4_REGIME_MISMATCH","H4_TREND_INELIGIBLE","H4_OVEREXTENDED","ENTRY_ZONE_INVALID","CANDIDATE_INVALID","NOT_ENTRY_M15_OPEN","SESSION_BLOCKED","NEWS_BLOCKED","POSITION_ALREADY_OPEN","NO_OPPOSING_ZONE","TARGET_ZONE_NOT_CAUSAL","TARGET_SPACE_BELOW_2R","INVALID_STOP","INVALID_MANAGEMENT_CONFIGURATION","RISK_SIZING_FAILED","VOLUME_INVALID","QUOTE_INVALID","EXECUTION_SAFETY_FAILED","DUPLICATE_PLAN","VALID_PLAN"};
   return(names[(int)value]);
  }
string E2V2ManagementBranchName(const E2V2ManagementBranch value)
  {return(value==E2_V2_MANAGEMENT_FIXED_2R?"FIXED_2R":value==E2_V2_MANAGEMENT_ZONE_TARGET_TRAILING?"ZONE_TARGET_TRAILING":"NONE");}

struct E2V2TradePlan
  {
   bool valid,trend_eligible_at_entry,overextended_at_entry,news_filter_enabled,position_exposure_clear;
   E2StrategyType strategy_type;E2TrendContinuationDirection direction;E2V2ManagementBranch management_branch;E2V2PlanReason reason;
   string candidate_id,plan_id,range_id,zone_id,target_zone_id,entry_quote_side;
   int zone_attempt;E2RegimeType h4_regime_at_candidate,h4_regime_at_entry;
   datetime breakout_candle_time,breakout_known_from,retest_time,retest_known_from,boundary_visit_time,boundary_visit_known_from,confirmation_candle_time,confirmation_known_from,entry_candle_time,entry_evaluation_time,target_zone_creation_time;
   double entry_h4_adx,bid,ask,planned_entry_price,actual_quote_entry,entry_zone_lower,entry_zone_upper,confirmation_frozen_h1_atr;
   double stop_zone_edge,stop_buffer_atr_multiple,structural_stop,normalized_stop,risk_distance;
   double target_near_edge,available_reward,available_r,planned_target;
   double initial_test_balance,risk_percent,fixed_risk_cash,raw_volume,normalized_volume,planned_monetary_risk;
   E2SessionResult session_result;E2NewsResult news_result;
  };

struct E2V2PlanVerification
  {
   int candidates_received,entry_windows_reached,plans_valid,plans_rejected,rejected_regime,rejected_overextension,rejected_zone,rejected_session,rejected_news,rejected_position,rejected_no_target,rejected_below_2r,rejected_stop,rejected_risk,rejected_management,rejected_other,fixed_2r_plans,zone_trailing_plans,long_plans,short_plans,duplicate_plans,plan_causality_violations;
   double average_available_r,median_available_r,minimum_available_r,maximum_available_r;
  };

struct E2RMRPlanVerification
  {
   int candidates_received,entry_windows_reached,plans_valid,plans_rejected,rejected_regime,rejected_range_invalid,rejected_source_zone,rejected_session,rejected_news,rejected_position,rejected_below_2r,rejected_stop,rejected_risk,rejected_management,rejected_other,long_plans,short_plans,duplicate_plans,plan_causality_violations;
   double average_available_r,minimum_available_r,maximum_available_r;
  };

class E2V2TradePlanEngine
  {
private:
   E2Config m_config;E2SymbolInfo *m_symbol_info;E2PositionSizer *m_sizer;E2PositionGuard *m_guard;E2SessionFilter *m_session;E2NewsFilter *m_news;E2Logger *m_logger;
   double m_initial_balance;string m_seen_candidates[];double m_available_r_values[];E2V2PlanVerification m_verify;E2RMRPlanVerification m_rmr_verify;double m_rmr_available_sum;
   bool Seen(const string id)const{for(int i=0;i<ArraySize(m_seen_candidates);i++)if(m_seen_candidates[i]==id)return(true);return(false);}
   void Remember(const string id){const int n=ArraySize(m_seen_candidates);ArrayResize(m_seen_candidates,n+1);m_seen_candidates[n]=id;}
   double NormalizeDown(const double value,const E2SymbolSpecification &spec)const{return(NormalizeDouble(MathFloor(value/spec.tick_size+1e-10)*spec.tick_size,spec.digits));}
   double NormalizeUp(const double value,const E2SymbolSpecification &spec)const{return(NormalizeDouble(MathCeil(value/spec.tick_size-1e-10)*spec.tick_size,spec.digits));}
   bool Reject(E2V2TradePlan &plan,const E2V2PlanReason reason)
     {plan.valid=false;plan.reason=reason;m_verify.plans_rejected++;switch(reason){case E2_V2_PLAN_H4_REGIME_MISMATCH:case E2_V2_PLAN_H4_TREND_INELIGIBLE:m_verify.rejected_regime++;break;case E2_V2_PLAN_H4_OVEREXTENDED:m_verify.rejected_overextension++;break;case E2_V2_PLAN_ENTRY_ZONE_INVALID:case E2_V2_PLAN_CANDIDATE_INVALID:m_verify.rejected_zone++;break;case E2_V2_PLAN_SESSION_BLOCKED:m_verify.rejected_session++;break;case E2_V2_PLAN_NEWS_BLOCKED:m_verify.rejected_news++;break;case E2_V2_PLAN_POSITION_ALREADY_OPEN:m_verify.rejected_position++;break;case E2_V2_PLAN_NO_OPPOSING_ZONE:case E2_V2_PLAN_TARGET_ZONE_NOT_CAUSAL:m_verify.rejected_no_target++;break;case E2_V2_PLAN_TARGET_SPACE_BELOW_2R:m_verify.rejected_below_2r++;break;case E2_V2_PLAN_INVALID_STOP:m_verify.rejected_stop++;break;case E2_V2_PLAN_RISK_SIZING_FAILED:case E2_V2_PLAN_VOLUME_INVALID:m_verify.rejected_risk++;break;case E2_V2_PLAN_INVALID_MANAGEMENT_CONFIGURATION:m_verify.rejected_management++;break;case E2_V2_PLAN_DUPLICATE:m_verify.duplicate_plans++;break;default:m_verify.rejected_other++;break;}if(m_logger!=NULL&&m_config.research_verbose_diagnostics)m_logger.Debug("candidate="+plan.candidate_id+", reason="+E2V2PlanReasonName(reason)+".","TCV2Plan");return(false);}
   bool Target(const E2TrendContinuationCandidate &candidate,const E2H1ZoneV2Record &zones[],const double entry,E2H1ZoneV2Record &selected,bool &noncausal)const
     {bool found=false;noncausal=false;double best=DBL_MAX;for(int i=0;i<ArraySize(zones);i++){if(zones[i].state!=E2_H1_ZONE_V2_ACTIVE)continue;const bool role=(candidate.direction==E2_TC_LONG?zones[i].type==E2_H1_ZONE_V2_RESISTANCE:zones[i].type==E2_H1_ZONE_V2_SUPPORT);if(!role)continue;const double edge=(candidate.direction==E2_TC_LONG?zones[i].lower:zones[i].upper);if((candidate.direction==E2_TC_LONG&&edge<=entry)||(candidate.direction==E2_TC_SHORT&&edge>=entry))continue;if(zones[i].creation_time>=candidate.candidate_known_from_time){noncausal=true;continue;}const double distance=MathAbs(edge-entry);if(!found||distance<best){found=true;best=distance;selected=zones[i];}}return(found);}
   void AddAvailableR(const double value){const int n=ArraySize(m_available_r_values);ArrayResize(m_available_r_values,n+1);m_available_r_values[n]=value;}
   bool ActiveZone(const E2H1ZoneV2Record &zones[],const string id)const{for(int i=0;i<ArraySize(zones);i++)if(zones[i].zone_id==id&&zones[i].state==E2_H1_ZONE_V2_ACTIVE)return(true);return(false);}
   bool RejectRMR(E2V2TradePlan &plan,const int category)
     {plan.valid=false;m_rmr_verify.plans_rejected++;switch(category){case 1:m_rmr_verify.rejected_regime++;break;case 2:m_rmr_verify.rejected_range_invalid++;break;case 3:m_rmr_verify.rejected_source_zone++;break;case 4:m_rmr_verify.rejected_session++;break;case 5:m_rmr_verify.rejected_news++;break;case 6:m_rmr_verify.rejected_position++;break;case 7:m_rmr_verify.rejected_below_2r++;break;case 8:m_rmr_verify.rejected_stop++;break;case 9:m_rmr_verify.rejected_risk++;break;case 10:m_rmr_verify.rejected_management++;break;case 11:m_rmr_verify.duplicate_plans++;break;default:m_rmr_verify.rejected_other++;break;}return(false);}
public:
   E2V2TradePlanEngine(void):m_symbol_info(NULL),m_sizer(NULL),m_guard(NULL),m_session(NULL),m_news(NULL),m_logger(NULL),m_initial_balance(0.0),m_rmr_available_sum(0.0){ZeroMemory(m_verify);ZeroMemory(m_rmr_verify);}
   void Initialize(const E2Config &config,E2SymbolInfo &symbol_info,E2PositionSizer &sizer,E2PositionGuard &guard,E2SessionFilter &session,E2NewsFilter &news,E2Logger &logger)
     {m_config=config;m_symbol_info=&symbol_info;m_sizer=&sizer;m_guard=&guard;m_session=&session;m_news=&news;m_logger=&logger;m_initial_balance=AccountInfoDouble(ACCOUNT_BALANCE);ArrayResize(m_seen_candidates,0);ArrayResize(m_available_r_values,0);ZeroMemory(m_verify);ZeroMemory(m_rmr_verify);m_rmr_available_sum=0.0;}
   bool RouteTrendContinuation(const string symbol,const datetime evaluation_time,const E2TrendContinuationCandidate &candidate,const E2H4RegimeResult &h4,const E2H1ZoneV2Record &zones[],E2V2TradePlan &plan)
     {
      ZeroMemory(plan);plan.strategy_type=E2_STRATEGY_TREND_CONTINUATION;plan.direction=candidate.direction;plan.candidate_id=candidate.candidate_id;plan.zone_id=candidate.source_zone_id;plan.zone_attempt=candidate.attempt_number;plan.h4_regime_at_candidate=candidate.h4_regime_at_confirmation;plan.h4_regime_at_entry=h4.regime;plan.trend_eligible_at_entry=h4.trend_entry_eligible;plan.overextended_at_entry=h4.trend_overextended;plan.entry_h4_adx=h4.adx;plan.breakout_candle_time=candidate.breakout_time;plan.breakout_known_from=candidate.breakout_known_from_time;plan.retest_time=candidate.retest_time;plan.retest_known_from=candidate.retest_known_from_time;plan.confirmation_candle_time=candidate.candidate_time;plan.confirmation_known_from=candidate.candidate_known_from_time;plan.entry_candle_time=candidate.candidate_known_from_time;plan.entry_evaluation_time=evaluation_time;plan.entry_zone_lower=candidate.zone_lower;plan.entry_zone_upper=candidate.zone_upper;plan.confirmation_frozen_h1_atr=candidate.confirmation_h1_atr;plan.stop_buffer_atr_multiple=m_config.research_h1_zone_invalidation_atr;plan.initial_test_balance=m_initial_balance;plan.risk_percent=m_config.risk_percent;plan.fixed_risk_cash=m_initial_balance*m_config.risk_percent/100.0;plan.news_filter_enabled=m_config.news_filter_enabled;m_verify.candidates_received++;
      if(Seen(candidate.candidate_id))return(Reject(plan,E2_V2_PLAN_DUPLICATE));Remember(candidate.candidate_id);
      if(!m_config.enable_trend_continuation)return(Reject(plan,E2_V2_PLAN_TREND_TOGGLE_DISABLED));
      const datetime entry_open=iTime(symbol,PERIOD_M15,0);if(entry_open!=candidate.candidate_known_from_time||evaluation_time<candidate.candidate_known_from_time||evaluation_time>=candidate.candidate_known_from_time+PeriodSeconds(PERIOD_M15))return(Reject(plan,E2_V2_PLAN_NOT_ENTRY_M15_OPEN));m_verify.entry_windows_reached++;
      if(candidate.state!=E2_TC_CONSUMED||candidate.confirmation_h1_atr<=0.0||candidate.zone_lower<=0.0||candidate.zone_upper<candidate.zone_lower)return(Reject(plan,E2_V2_PLAN_CANDIDATE_INVALID));
      if(candidate.direction==E2_TC_LONG?h4.regime!=E2_REGIME_UPTREND:h4.regime!=E2_REGIME_DOWNTREND)return(Reject(plan,E2_V2_PLAN_H4_REGIME_MISMATCH));
      if(!h4.trend_entry_eligible)return(Reject(plan,E2_V2_PLAN_H4_TREND_INELIGIBLE));if(h4.trend_overextended)return(Reject(plan,E2_V2_PLAN_H4_OVEREXTENDED));
      if(m_guard==NULL||m_guard.HasOpenE2Position(symbol))return(Reject(plan,E2_V2_PLAN_POSITION_ALREADY_OPEN));plan.position_exposure_clear=true;
      if(m_session==NULL||!m_session.Evaluate(evaluation_time,plan.session_result)||!plan.session_result.eligible)return(Reject(plan,E2_V2_PLAN_SESSION_BLOCKED));
      if(m_news==NULL||!m_news.Evaluate(symbol,evaluation_time,plan.news_result)||!plan.news_result.eligible)return(Reject(plan,E2_V2_PLAN_NEWS_BLOCKED));
      if(m_symbol_info==NULL||!m_symbol_info.Refresh(symbol))return(Reject(plan,E2_V2_PLAN_EXECUTION_SAFETY_FAILED));const E2SymbolSpecification spec=m_symbol_info.Specification();if(spec.trade_mode==SYMBOL_TRADE_MODE_DISABLED||spec.trade_mode==SYMBOL_TRADE_MODE_CLOSEONLY||(candidate.direction==E2_TC_LONG&&spec.trade_mode==SYMBOL_TRADE_MODE_SHORTONLY)||(candidate.direction==E2_TC_SHORT&&spec.trade_mode==SYMBOL_TRADE_MODE_LONGONLY))return(Reject(plan,E2_V2_PLAN_EXECUTION_SAFETY_FAILED));MqlTick tick;if(!SymbolInfoTick(symbol,tick)||tick.bid<=0.0||tick.ask<tick.bid||tick.time<=0)return(Reject(plan,E2_V2_PLAN_QUOTE_INVALID));
      if(m_config.max_quote_age_seconds>0&&evaluation_time-tick.time>m_config.max_quote_age_seconds)return(Reject(plan,E2_V2_PLAN_QUOTE_INVALID));const double spread=(tick.ask-tick.bid)/spec.pip_size;if(m_config.max_spread_pips>0.0&&spread>m_config.max_spread_pips+1e-9)return(Reject(plan,E2_V2_PLAN_EXECUTION_SAFETY_FAILED));
      plan.bid=tick.bid;plan.ask=tick.ask;plan.actual_quote_entry=(candidate.direction==E2_TC_LONG?tick.ask:tick.bid);plan.planned_entry_price=plan.actual_quote_entry;plan.entry_quote_side=(candidate.direction==E2_TC_LONG?"ASK":"BID");
      plan.stop_zone_edge=(candidate.direction==E2_TC_LONG?candidate.zone_lower:candidate.zone_upper);plan.structural_stop=(candidate.direction==E2_TC_LONG?plan.stop_zone_edge-plan.stop_buffer_atr_multiple*candidate.confirmation_h1_atr:plan.stop_zone_edge+plan.stop_buffer_atr_multiple*candidate.confirmation_h1_atr);plan.normalized_stop=(candidate.direction==E2_TC_LONG?NormalizeDown(plan.structural_stop,spec):NormalizeUp(plan.structural_stop,spec));
      const double minimum=spec.stops_level_points*spec.point;if(minimum>0.0&&MathAbs(plan.actual_quote_entry-plan.normalized_stop)+1e-12<minimum)plan.normalized_stop=(candidate.direction==E2_TC_LONG?NormalizeDown(plan.actual_quote_entry-minimum,spec):NormalizeUp(plan.actual_quote_entry+minimum,spec));if((candidate.direction==E2_TC_LONG&&plan.structural_stop>=plan.actual_quote_entry)||(candidate.direction==E2_TC_SHORT&&plan.structural_stop<=plan.actual_quote_entry))return(Reject(plan,E2_V2_PLAN_INVALID_STOP));plan.risk_distance=MathAbs(plan.actual_quote_entry-plan.normalized_stop);if(plan.risk_distance<spec.tick_size-1e-12)return(Reject(plan,E2_V2_PLAN_INVALID_STOP));
      E2H1ZoneV2Record target;bool noncausal=false;if(!Target(candidate,zones,plan.actual_quote_entry,target,noncausal))return(Reject(plan,noncausal?E2_V2_PLAN_TARGET_ZONE_NOT_CAUSAL:E2_V2_PLAN_NO_OPPOSING_ZONE));plan.target_zone_id=target.zone_id;plan.target_zone_creation_time=target.creation_time;plan.target_near_edge=(candidate.direction==E2_TC_LONG?target.lower:target.upper);if(plan.target_zone_creation_time>=plan.confirmation_known_from)m_verify.plan_causality_violations++;
      plan.available_reward=(candidate.direction==E2_TC_LONG?plan.target_near_edge-plan.actual_quote_entry:plan.actual_quote_entry-plan.target_near_edge);plan.available_r=plan.available_reward/plan.risk_distance;if(plan.available_r<2.0-1e-10)return(Reject(plan,E2_V2_PLAN_TARGET_SPACE_BELOW_2R));
      if(m_config.enable_fixed_2r_management==m_config.enable_zone_target_trailing_management)return(Reject(plan,E2_V2_PLAN_INVALID_MANAGEMENT_CONFIGURATION));if(m_config.enable_zone_target_trailing_management){if(plan.available_r<3.0-1e-10)return(Reject(plan,E2_V2_PLAN_INVALID_MANAGEMENT_CONFIGURATION));plan.management_branch=E2_V2_MANAGEMENT_ZONE_TARGET_TRAILING;plan.planned_target=plan.target_near_edge;}else{plan.management_branch=E2_V2_MANAGEMENT_FIXED_2R;const double raw=(candidate.direction==E2_TC_LONG?plan.actual_quote_entry+2.0*plan.risk_distance:plan.actual_quote_entry-2.0*plan.risk_distance);plan.planned_target=m_symbol_info.NormalizePrice(raw);}
      E2PositionSizingResult sizing;if(m_sizer==NULL||!m_sizer.CalculateFixedInitialBalance(symbol,candidate.direction==E2_TC_LONG?E2_DIRECTION_BUY:E2_DIRECTION_SELL,plan.actual_quote_entry,plan.normalized_stop,m_initial_balance,sizing))return(Reject(plan,E2_V2_PLAN_RISK_SIZING_FAILED));if(sizing.volume<=0.0)return(Reject(plan,E2_V2_PLAN_VOLUME_INVALID));plan.raw_volume=sizing.raw_volume;plan.normalized_volume=sizing.volume;plan.planned_monetary_risk=sizing.actual_risk_money;plan.fixed_risk_cash=sizing.target_risk_money;
      plan.valid=true;plan.reason=E2_V2_PLAN_VALID;m_verify.plans_valid++;if(plan.management_branch==E2_V2_MANAGEMENT_FIXED_2R)m_verify.fixed_2r_plans++;else m_verify.zone_trailing_plans++;if(candidate.direction==E2_TC_LONG)m_verify.long_plans++;else m_verify.short_plans++;AddAvailableR(plan.available_r);if(m_logger!=NULL&&m_config.research_verbose_diagnostics)m_logger.Debug("candidate="+plan.candidate_id+", entry="+DoubleToString(plan.actual_quote_entry,spec.digits)+", stop="+DoubleToString(plan.normalized_stop,spec.digits)+", target="+DoubleToString(plan.planned_target,spec.digits)+", availableR="+DoubleToString(plan.available_r,3)+", branch="+E2V2ManagementBranchName(plan.management_branch)+".","TCV2Plan");return(true);
     }
   bool RouteRangeMeanReversion(const string symbol,const datetime evaluation_time,const E2RangeMeanReversionCandidate &candidate,const E2H4RegimeResult &h4,const E2H1RangeBoundaryContext &range,const E2H1ZoneV2Record &zones[],E2V2TradePlan &plan)
     {
      ZeroMemory(plan);plan.strategy_type=E2_STRATEGY_RANGE_MEAN_REVERSION;plan.direction=(candidate.direction==E2_RMR_LONG?E2_TC_LONG:E2_TC_SHORT);plan.candidate_id=candidate.candidate_id;plan.plan_id="RMRP_"+candidate.candidate_id+"_"+IntegerToString((int)candidate.confirmation_known_from);plan.range_id=candidate.range_id;plan.zone_id=candidate.source_zone_id;plan.target_zone_id=(candidate.direction==E2_RMR_LONG?candidate.upper_zone_id:candidate.lower_zone_id);plan.zone_attempt=candidate.attempt_number;plan.h4_regime_at_candidate=candidate.h4_regime;plan.h4_regime_at_entry=h4.regime;plan.entry_h4_adx=h4.adx;plan.boundary_visit_time=candidate.boundary_visit_time;plan.boundary_visit_known_from=candidate.boundary_visit_known_from;plan.confirmation_candle_time=candidate.confirmation_candle;plan.confirmation_known_from=candidate.confirmation_known_from;plan.entry_candle_time=candidate.confirmation_known_from;plan.entry_evaluation_time=evaluation_time;plan.entry_zone_lower=candidate.source_zone_lower;plan.entry_zone_upper=candidate.source_zone_upper;plan.confirmation_frozen_h1_atr=candidate.confirmation_h1_atr;plan.stop_buffer_atr_multiple=m_config.research_h1_zone_invalidation_atr;plan.initial_test_balance=m_initial_balance;plan.risk_percent=m_config.risk_percent;plan.fixed_risk_cash=m_initial_balance*m_config.risk_percent/100.0;plan.news_filter_enabled=m_config.news_filter_enabled;m_rmr_verify.candidates_received++;
      if(Seen(plan.plan_id))return(RejectRMR(plan,11));Remember(plan.plan_id);if(!m_config.enable_range_mean_reversion)return(RejectRMR(plan,0));const datetime entry_open=iTime(symbol,PERIOD_M15,0);if(entry_open!=candidate.confirmation_known_from||evaluation_time<candidate.confirmation_known_from||evaluation_time>=candidate.confirmation_known_from+PeriodSeconds(PERIOD_M15))return(RejectRMR(plan,0));m_rmr_verify.entry_windows_reached++;
      if(candidate.setup_type!=E2_STRATEGY_RANGE_MEAN_REVERSION||candidate.confirmation_known_from<candidate.range_known_from||candidate.confirmation_known_from<candidate.boundary_visit_known_from||candidate.confirmation_known_from>evaluation_time){m_rmr_verify.plan_causality_violations++;return(RejectRMR(plan,0));}
      if(h4.regime!=E2_REGIME_RANGE)return(RejectRMR(plan,1));if(!range.valid||range.range_id!=candidate.range_id)return(RejectRMR(plan,2));if(!ActiveZone(zones,candidate.source_zone_id)||!ActiveZone(zones,plan.target_zone_id))return(RejectRMR(plan,3));
      if(m_guard==NULL||m_guard.HasOpenE2Position(symbol))return(RejectRMR(plan,6));plan.position_exposure_clear=true;if(m_session==NULL||!m_session.Evaluate(evaluation_time,plan.session_result)||!plan.session_result.eligible)return(RejectRMR(plan,4));if(m_news==NULL||!m_news.Evaluate(symbol,evaluation_time,plan.news_result)||!plan.news_result.eligible)return(RejectRMR(plan,5));
      if(m_symbol_info==NULL||!m_symbol_info.Refresh(symbol))return(RejectRMR(plan,0));const E2SymbolSpecification spec=m_symbol_info.Specification();if(spec.trade_mode==SYMBOL_TRADE_MODE_DISABLED||spec.trade_mode==SYMBOL_TRADE_MODE_CLOSEONLY||(plan.direction==E2_TC_LONG&&spec.trade_mode==SYMBOL_TRADE_MODE_SHORTONLY)||(plan.direction==E2_TC_SHORT&&spec.trade_mode==SYMBOL_TRADE_MODE_LONGONLY))return(RejectRMR(plan,0));MqlTick tick;if(!SymbolInfoTick(symbol,tick)||tick.bid<=0.0||tick.ask<tick.bid||tick.time<=0)return(RejectRMR(plan,0));if(m_config.max_quote_age_seconds>0&&evaluation_time-tick.time>m_config.max_quote_age_seconds)return(RejectRMR(plan,0));const double spread=(tick.ask-tick.bid)/spec.pip_size;if(m_config.max_spread_pips>0.0&&spread>m_config.max_spread_pips+1e-9)return(RejectRMR(plan,0));
      plan.bid=tick.bid;plan.ask=tick.ask;plan.actual_quote_entry=(plan.direction==E2_TC_LONG?tick.ask:tick.bid);plan.planned_entry_price=plan.actual_quote_entry;plan.entry_quote_side=(plan.direction==E2_TC_LONG?"ASK":"BID");plan.stop_zone_edge=(plan.direction==E2_TC_LONG?candidate.source_zone_lower:candidate.source_zone_upper);plan.structural_stop=(plan.direction==E2_TC_LONG?plan.stop_zone_edge-plan.stop_buffer_atr_multiple*candidate.confirmation_h1_atr:plan.stop_zone_edge+plan.stop_buffer_atr_multiple*candidate.confirmation_h1_atr);plan.normalized_stop=(plan.direction==E2_TC_LONG?NormalizeDown(plan.structural_stop,spec):NormalizeUp(plan.structural_stop,spec));const double minimum=spec.stops_level_points*spec.point;if(minimum>0.0&&MathAbs(plan.actual_quote_entry-plan.normalized_stop)+1e-12<minimum)plan.normalized_stop=(plan.direction==E2_TC_LONG?NormalizeDown(plan.actual_quote_entry-minimum,spec):NormalizeUp(plan.actual_quote_entry+minimum,spec));if(candidate.confirmation_h1_atr<=0.0||(plan.direction==E2_TC_LONG&&plan.structural_stop>=plan.actual_quote_entry)||(plan.direction==E2_TC_SHORT&&plan.structural_stop<=plan.actual_quote_entry))return(RejectRMR(plan,8));plan.risk_distance=MathAbs(plan.actual_quote_entry-plan.normalized_stop);if(plan.risk_distance<spec.tick_size-1e-12)return(RejectRMR(plan,8));
      plan.target_near_edge=(plan.direction==E2_TC_LONG?candidate.upper_zone_lower:candidate.lower_zone_upper);plan.planned_target=(plan.direction==E2_TC_LONG?NormalizeDown(plan.target_near_edge,spec):NormalizeUp(plan.target_near_edge,spec));plan.available_reward=(plan.direction==E2_TC_LONG?plan.target_near_edge-plan.actual_quote_entry:plan.actual_quote_entry-plan.target_near_edge);plan.available_r=plan.available_reward/plan.risk_distance;if(plan.available_r<2.0-1e-10)return(RejectRMR(plan,7));plan.management_branch=E2_V2_MANAGEMENT_ZONE_TARGET_TRAILING;
      E2PositionSizingResult sizing;if(m_sizer==NULL||!m_sizer.CalculateFixedInitialBalance(symbol,plan.direction==E2_TC_LONG?E2_DIRECTION_BUY:E2_DIRECTION_SELL,plan.actual_quote_entry,plan.normalized_stop,m_initial_balance,sizing)||sizing.volume<=0.0)return(RejectRMR(plan,9));plan.raw_volume=sizing.raw_volume;plan.normalized_volume=sizing.volume;plan.planned_monetary_risk=sizing.actual_risk_money;plan.fixed_risk_cash=sizing.target_risk_money;plan.valid=true;plan.reason=E2_V2_PLAN_VALID;m_rmr_verify.plans_valid++;if(plan.direction==E2_TC_LONG)m_rmr_verify.long_plans++;else m_rmr_verify.short_plans++;m_rmr_available_sum+=plan.available_r;if(m_rmr_verify.plans_valid==1){m_rmr_verify.minimum_available_r=plan.available_r;m_rmr_verify.maximum_available_r=plan.available_r;}else{m_rmr_verify.minimum_available_r=MathMin(m_rmr_verify.minimum_available_r,plan.available_r);m_rmr_verify.maximum_available_r=MathMax(m_rmr_verify.maximum_available_r,plan.available_r);}return(true);
     }
   E2V2PlanVerification Verification()
     {E2V2PlanVerification value=m_verify;const int n=ArraySize(m_available_r_values);if(n>0){double sorted[];ArrayResize(sorted,n);double sum=0.0;for(int i=0;i<n;i++){sorted[i]=m_available_r_values[i];sum+=sorted[i];}for(int i=1;i<n;i++){const double x=sorted[i];int j=i-1;while(j>=0&&sorted[j]>x){sorted[j+1]=sorted[j];j--;}sorted[j+1]=x;}value.average_available_r=sum/n;value.median_available_r=(n%2==1?sorted[n/2]:(sorted[n/2-1]+sorted[n/2])/2.0);value.minimum_available_r=sorted[0];value.maximum_available_r=sorted[n-1];}return(value);}
   E2RMRPlanVerification RMRVerification()const{E2RMRPlanVerification value=m_rmr_verify;if(value.plans_valid>0)value.average_available_r=m_rmr_available_sum/value.plans_valid;return(value);}
  };

#endif
