#ifndef E2_EXECUTION_E2V2EXECUTIONENGINE_MQH
#define E2_EXECUTION_E2V2EXECUTIONENGINE_MQH

#include "..\strategy\E2V2TradePlanEngine.mqh"
#include "E2OrderExecutor.mqh"
#include "..\reporting\E2TradeReporter.mqh"

enum E2V2ExecutionStatus
  {E2_V2_EXECUTION_SUCCESS,E2_V2_EXECUTION_REJECTED,E2_V2_EXECUTION_INVALID_PRICE,E2_V2_EXECUTION_INVALID_STOPS,E2_V2_EXECUTION_INVALID_VOLUME,E2_V2_EXECUTION_NO_MONEY,E2_V2_EXECUTION_MARKET_CLOSED,E2_V2_EXECUTION_POSITION_EXISTS,E2_V2_EXECUTION_RR_INVALID,E2_V2_EXECUTION_DISABLED,E2_V2_EXECUTION_OTHER_FAILURE};
enum E2V2ManagementState { E2_V2_MANAGEMENT_STATE_INITIAL };

struct E2V2PositionMetadata
  {
   ulong position_id,order_ticket,deal_ticket;string symbol,plan_id,candidate_id,zone_id,target_zone_id;E2TradeDirection direction;E2StrategyType strategy_type;int zone_attempt;
   datetime entry_time;double planned_entry,execution_quote,entry_price,structural_stop,submitted_stop,initial_stop,initial_risk_distance,fixed_risk_cash,actual_initial_risk_cash,initial_tp,initial_r_price_distance,target_near_edge,available_r_at_plan;
   E2V2ManagementBranch management_branch;E2V2ManagementState management_state;
  };
struct E2V2ExecutionResult
  {E2V2ExecutionStatus status;string plan_id;datetime execution_time;double planned_entry,execution_quote,quote_difference,actual_fill,fill_slippage,submitted_stop,submitted_tp,raw_volume,normalized_volume,estimated_risk_cash,actual_initial_risk_distance,actual_initial_risk_cash,actual_initial_r;uint retcode;ulong order_ticket,deal_ticket,position_id;};
struct E2V2ExecutionVerification
  {
   int valid_plans_received,execution_disabled,execution_attempts,execution_successes,execution_failures,long_attempts,short_attempts,fixed_2r_attempts,zone_trailing_attempts,rejected_position_open,rejected_quote,rejected_stops,rejected_volume,rejected_rr,rejected_margin,rejected_market,rejected_other,duplicate_execution_attempts,successful_positions_registered,metadata_registration_failures,unaccounted_valid_plans,execution_causality_violations;
   double average_planned_to_quote_difference,average_quote_to_fill_slippage,average_actual_risk_cash,max_actual_risk_deviation_percent;
  };

class E2V2ExecutionEngine
  {
private:
   E2Config m_config;E2SymbolInfo *m_symbol_info;E2PositionSizer *m_sizer;E2PositionGuard *m_guard;E2OrderExecutor *m_executor;E2TradeReporter *m_reporter;E2Logger *m_logger;
   string m_attempted[];E2V2PositionMetadata m_metadata[];E2V2ExecutionVerification m_verify;double m_quote_diff_sum,m_slippage_sum,m_risk_sum;
   bool Attempted(const string id)const{for(int i=0;i<ArraySize(m_attempted);i++)if(m_attempted[i]==id)return(true);return(false);}
   void Remember(const string id){const int n=ArraySize(m_attempted);ArrayResize(m_attempted,n+1);m_attempted[n]=id;}
   double NormalizeDown(const double value,const E2SymbolSpecification &spec)const{return(NormalizeDouble(MathFloor(value/spec.tick_size+1e-10)*spec.tick_size,spec.digits));}
   double NormalizeUp(const double value,const E2SymbolSpecification &spec)const{return(NormalizeDouble(MathCeil(value/spec.tick_size-1e-10)*spec.tick_size,spec.digits));}
   bool ActualRisk(const string symbol,const E2TradeDirection direction,const double volume,const double entry,const double stop,double &risk)const{double profit=0.0;const ENUM_ORDER_TYPE type=(direction==E2_DIRECTION_BUY?ORDER_TYPE_BUY:ORDER_TYPE_SELL);if(!OrderCalcProfit(type,symbol,volume,entry,stop,profit))return(false);risk=MathAbs(profit);return(risk>0.0);}
   E2V2ExecutionStatus Map(const E2ExecutionStatus status)const
     {switch(status){case E2_EXECUTION_EXECUTED:return(E2_V2_EXECUTION_SUCCESS);case E2_EXECUTION_TRADING_DISABLED:return(E2_V2_EXECUTION_DISABLED);case E2_EXECUTION_POSITION_ALREADY_OPEN:case E2_EXECUTION_PENDING_ORDER_EXISTS:case E2_EXECUTION_DIRECTION_CONFLICT:return(E2_V2_EXECUTION_POSITION_EXISTS);case E2_EXECUTION_NO_VALID_QUOTE:case E2_EXECUTION_MARKET_PRICE_UNAVAILABLE:case E2_EXECUTION_PRICE_DEVIATION_EXCEEDED:return(E2_V2_EXECUTION_INVALID_PRICE);case E2_EXECUTION_INVALID_CURRENT_GEOMETRY:case E2_EXECUTION_BROKER_STOP_CONSTRAINT:return(E2_V2_EXECUTION_INVALID_STOPS);case E2_EXECUTION_VOLUME_INVALID:return(E2_V2_EXECUTION_INVALID_VOLUME);case E2_EXECUTION_MARGIN_INSUFFICIENT:case E2_EXECUTION_INSUFFICIENT_MARGIN:return(E2_V2_EXECUTION_NO_MONEY);case E2_EXECUTION_MARKET_CLOSED:return(E2_V2_EXECUTION_MARKET_CLOSED);case E2_EXECUTION_ORDER_REJECTED:return(E2_V2_EXECUTION_REJECTED);default:return(E2_V2_EXECUTION_OTHER_FAILURE);}}
   bool Fail(E2V2ExecutionResult &result,const E2V2ExecutionStatus status)
     {result.status=status;m_verify.execution_failures++;switch(status){case E2_V2_EXECUTION_POSITION_EXISTS:m_verify.rejected_position_open++;break;case E2_V2_EXECUTION_INVALID_PRICE:m_verify.rejected_quote++;break;case E2_V2_EXECUTION_INVALID_STOPS:m_verify.rejected_stops++;break;case E2_V2_EXECUTION_INVALID_VOLUME:m_verify.rejected_volume++;break;case E2_V2_EXECUTION_RR_INVALID:m_verify.rejected_rr++;break;case E2_V2_EXECUTION_NO_MONEY:m_verify.rejected_margin++;break;case E2_V2_EXECUTION_MARKET_CLOSED:m_verify.rejected_market++;break;default:m_verify.rejected_other++;break;}return(false);}
   bool Register(const E2V2TradePlan &plan,const E2V2ExecutionResult &result,E2V2PositionMetadata &metadata)
     {
      if(result.deal_ticket==0||!HistorySelect(0,TimeCurrent())||!HistoryDealSelect(result.deal_ticket))return(false);const ulong position=(ulong)HistoryDealGetInteger(result.deal_ticket,DEAL_POSITION_ID);if(position==0)return(false);ZeroMemory(metadata);metadata.position_id=position;metadata.order_ticket=result.order_ticket;metadata.deal_ticket=result.deal_ticket;metadata.symbol=Symbol();metadata.plan_id=result.plan_id;metadata.candidate_id=plan.candidate_id;metadata.zone_id=plan.zone_id;metadata.zone_attempt=plan.zone_attempt;metadata.target_zone_id=plan.target_zone_id;metadata.direction=(plan.direction==E2_TC_LONG?E2_DIRECTION_BUY:E2_DIRECTION_SELL);metadata.strategy_type=plan.strategy_type;metadata.entry_time=(datetime)HistoryDealGetInteger(result.deal_ticket,DEAL_TIME);metadata.planned_entry=plan.planned_entry_price;metadata.execution_quote=result.execution_quote;metadata.entry_price=result.actual_fill;metadata.structural_stop=plan.structural_stop;metadata.submitted_stop=result.submitted_stop;metadata.initial_stop=result.submitted_stop;metadata.initial_risk_distance=result.actual_initial_risk_distance;metadata.fixed_risk_cash=plan.fixed_risk_cash;metadata.actual_initial_risk_cash=result.actual_initial_risk_cash;metadata.management_branch=plan.management_branch;metadata.target_near_edge=plan.target_near_edge;metadata.available_r_at_plan=plan.available_r;metadata.initial_tp=result.submitted_tp;metadata.initial_r_price_distance=result.actual_initial_risk_distance;metadata.management_state=E2_V2_MANAGEMENT_STATE_INITIAL;const int n=ArraySize(m_metadata);ArrayResize(m_metadata,n+1);m_metadata[n]=metadata;return(true);
     }
   void CaptureReport(const E2V2TradePlan &plan,const E2V2ExecutionResult &result)const
     {if(m_reporter==NULL)return;E2ReportEntryData entry;ZeroMemory(entry);entry.symbol=Symbol();entry.direction=(plan.direction==E2_TC_LONG?"LONG":"SHORT");entry.zone_role=(plan.direction==E2_TC_LONG?"SUPPORT":"RESISTANCE");entry.zone_visit=plan.zone_attempt;entry.signal_time=plan.confirmation_known_from;entry.confirmation_time=plan.confirmation_candle_time;entry.entry_time=result.execution_time;entry.planned_entry=plan.planned_entry_price;entry.fill_price=result.actual_fill;entry.stop_loss=result.submitted_stop;entry.take_profit=result.submitted_tp;entry.stop_pips=(m_symbol_info!=NULL?result.actual_initial_risk_distance/m_symbol_info.Specification().pip_size:0.0);entry.planned_rr=(plan.management_branch==E2_V2_MANAGEMENT_FIXED_2R?2.0:plan.available_r);entry.volume=result.normalized_volume;entry.equity=AccountInfoDouble(ACCOUNT_EQUITY);entry.target_risk=plan.fixed_risk_cash;entry.planned_risk=result.actual_initial_risk_cash;entry.planned_risk_pct=(plan.initial_test_balance>0.0?result.actual_initial_risk_cash/plan.initial_test_balance*100.0:0.0);entry.order_ticket=result.order_ticket;entry.entry_deal=result.deal_ticket;m_reporter.CaptureEntry(entry);}
public:
   E2V2ExecutionEngine(void):m_symbol_info(NULL),m_sizer(NULL),m_guard(NULL),m_executor(NULL),m_reporter(NULL),m_logger(NULL),m_quote_diff_sum(0.0),m_slippage_sum(0.0),m_risk_sum(0.0){ZeroMemory(m_verify);}
   void Initialize(const E2Config &config,E2SymbolInfo &symbol_info,E2PositionSizer &sizer,E2PositionGuard &guard,E2OrderExecutor &executor,E2TradeReporter &reporter,E2Logger &logger)
     {m_config=config;m_symbol_info=&symbol_info;m_sizer=&sizer;m_guard=&guard;m_executor=&executor;m_reporter=&reporter;m_logger=&logger;ArrayResize(m_attempted,0);ArrayResize(m_metadata,0);ZeroMemory(m_verify);m_quote_diff_sum=0.0;m_slippage_sum=0.0;m_risk_sum=0.0;}
   bool Execute(const string symbol,const E2V2TradePlan &plan,E2V2ExecutionResult &result)
     {
      ZeroMemory(result);result.status=E2_V2_EXECUTION_OTHER_FAILURE;result.plan_id="V2P_"+plan.candidate_id;result.planned_entry=plan.planned_entry_price;m_verify.valid_plans_received++;
      if(Attempted(result.plan_id)){m_verify.duplicate_execution_attempts++;return(false);}Remember(result.plan_id);
      if(!m_config.trading_enabled){result.status=E2_V2_EXECUTION_DISABLED;m_verify.execution_disabled++;return(false);}m_verify.execution_attempts++;if(plan.direction==E2_TC_LONG)m_verify.long_attempts++;else m_verify.short_attempts++;if(plan.management_branch==E2_V2_MANAGEMENT_FIXED_2R)m_verify.fixed_2r_attempts++;else m_verify.zone_trailing_attempts++;
      if(!plan.valid||plan.entry_evaluation_time<plan.entry_candle_time||plan.entry_evaluation_time>=plan.entry_candle_time+PeriodSeconds(PERIOD_M15)){m_verify.execution_causality_violations++;return(Fail(result,E2_V2_EXECUTION_OTHER_FAILURE));}
      if(m_guard==NULL||m_guard.HasOpenE2Position(symbol))return(Fail(result,E2_V2_EXECUTION_POSITION_EXISTS));if(m_symbol_info==NULL||!m_symbol_info.Refresh(symbol))return(Fail(result,E2_V2_EXECUTION_INVALID_PRICE));const E2SymbolSpecification spec=m_symbol_info.Specification();MqlTick tick;if(!SymbolInfoTick(symbol,tick)||tick.bid<=0.0||tick.ask<tick.bid||tick.time<=0)return(Fail(result,E2_V2_EXECUTION_INVALID_PRICE));result.execution_time=TimeCurrent();result.execution_quote=(plan.direction==E2_TC_LONG?tick.ask:tick.bid);result.quote_difference=result.execution_quote-plan.planned_entry_price;m_quote_diff_sum+=MathAbs(result.quote_difference);
      const double minimum=MathMax((double)SymbolInfoInteger(symbol,SYMBOL_TRADE_STOPS_LEVEL),(double)SymbolInfoInteger(symbol,SYMBOL_TRADE_FREEZE_LEVEL))*spec.point;result.submitted_stop=(plan.direction==E2_TC_LONG?NormalizeDown(plan.structural_stop,spec):NormalizeUp(plan.structural_stop,spec));if(minimum>0.0&&MathAbs(result.execution_quote-result.submitted_stop)+1e-12<minimum)result.submitted_stop=(plan.direction==E2_TC_LONG?NormalizeDown(result.execution_quote-minimum,spec):NormalizeUp(result.execution_quote+minimum,spec));if((plan.direction==E2_TC_LONG&&result.submitted_stop>=result.execution_quote)||(plan.direction==E2_TC_SHORT&&result.submitted_stop<=result.execution_quote))return(Fail(result,E2_V2_EXECUTION_INVALID_STOPS));const double risk_distance=MathAbs(result.execution_quote-result.submitted_stop);const double reward=(plan.direction==E2_TC_LONG?plan.target_near_edge-result.execution_quote:result.execution_quote-plan.target_near_edge);if(risk_distance<=0.0||reward/risk_distance<2.0-1e-10)return(Fail(result,E2_V2_EXECUTION_RR_INVALID));
      if(plan.management_branch==E2_V2_MANAGEMENT_FIXED_2R){const double raw=(plan.direction==E2_TC_LONG?result.execution_quote+2.0*risk_distance:result.execution_quote-2.0*risk_distance);result.submitted_tp=(plan.direction==E2_TC_LONG?NormalizeUp(raw,spec):NormalizeDown(raw,spec));}else result.submitted_tp=(plan.direction==E2_TC_LONG?NormalizeDown(plan.target_near_edge,spec):NormalizeUp(plan.target_near_edge,spec));if((plan.direction==E2_TC_LONG&&result.submitted_tp<=result.execution_quote)||(plan.direction==E2_TC_SHORT&&result.submitted_tp>=result.execution_quote))return(Fail(result,E2_V2_EXECUTION_INVALID_STOPS));
      E2PositionSizingResult sizing;if(m_sizer==NULL||!m_sizer.CalculateFixedInitialBalance(symbol,plan.direction==E2_TC_LONG?E2_DIRECTION_BUY:E2_DIRECTION_SELL,result.execution_quote,result.submitted_stop,plan.initial_test_balance,sizing))return(Fail(result,sizing.status==E2_SIZING_VOLUME_BELOW_MINIMUM||sizing.status==E2_SIZING_VOLUME_ABOVE_MAXIMUM?E2_V2_EXECUTION_INVALID_VOLUME:E2_V2_EXECUTION_OTHER_FAILURE));result.raw_volume=sizing.raw_volume;result.normalized_volume=sizing.volume;result.estimated_risk_cash=sizing.actual_risk_money;if(result.normalized_volume<=0.0)return(Fail(result,E2_V2_EXECUTION_INVALID_VOLUME));
      E2TradePlan native_plan;ZeroMemory(native_plan);native_plan.ready=true;native_plan.valid=true;native_plan.status=E2_PLAN_VALID;native_plan.symbol=symbol;native_plan.direction=(plan.direction==E2_TC_LONG?E2_DIRECTION_BUY:E2_DIRECTION_SELL);native_plan.entry_price=result.execution_quote;native_plan.stop_loss_price=result.submitted_stop;native_plan.take_profit_price=result.submitted_tp;native_plan.volume=result.normalized_volume;native_plan.raw_volume=result.raw_volume;native_plan.target_risk_money=plan.fixed_risk_cash;native_plan.actual_risk_money=result.estimated_risk_cash;native_plan.risk_percent=plan.risk_percent;native_plan.stop_distance_price=risk_distance;native_plan.stop_distance_pips=risk_distance/spec.pip_size;native_plan.actual_reward_risk=MathAbs(result.submitted_tp-result.execution_quote)/risk_distance;
      const string comment="E2V2|"+IntegerToString((int)plan.confirmation_known_from)+"|"+IntegerToString(plan.zone_attempt);E2ExecutionResult native_result;if(m_executor==NULL||!m_executor.Execute(native_plan,comment,native_result)){result.retcode=native_result.retcode;result.order_ticket=native_result.order_ticket;result.deal_ticket=native_result.deal_ticket;return(Fail(result,m_executor==NULL?E2_V2_EXECUTION_OTHER_FAILURE:Map(native_result.status)));}
      result.status=E2_V2_EXECUTION_SUCCESS;result.retcode=native_result.retcode;result.order_ticket=native_result.order_ticket;result.deal_ticket=native_result.deal_ticket;result.actual_fill=native_result.actual_execution_price;if(result.deal_ticket>0&&HistorySelect(0,TimeCurrent())&&HistoryDealSelect(result.deal_ticket)){result.actual_fill=HistoryDealGetDouble(result.deal_ticket,DEAL_PRICE);result.execution_time=(datetime)HistoryDealGetInteger(result.deal_ticket,DEAL_TIME);result.position_id=(ulong)HistoryDealGetInteger(result.deal_ticket,DEAL_POSITION_ID);}result.fill_slippage=result.actual_fill-result.execution_quote;result.actual_initial_risk_distance=MathAbs(result.actual_fill-result.submitted_stop);if(!ActualRisk(symbol,native_plan.direction,result.normalized_volume,result.actual_fill,result.submitted_stop,result.actual_initial_risk_cash))result.actual_initial_risk_cash=result.estimated_risk_cash;result.actual_initial_r=(result.actual_initial_risk_distance>0.0?MathAbs(result.submitted_tp-result.actual_fill)/result.actual_initial_risk_distance:0.0);m_verify.execution_successes++;m_slippage_sum+=MathAbs(result.fill_slippage);m_risk_sum+=result.actual_initial_risk_cash;const double deviation=(plan.fixed_risk_cash>0.0?MathAbs(result.actual_initial_risk_cash-plan.fixed_risk_cash)/plan.fixed_risk_cash*100.0:0.0);m_verify.max_actual_risk_deviation_percent=MathMax(m_verify.max_actual_risk_deviation_percent,deviation);
      E2V2PositionMetadata metadata;if(Register(plan,result,metadata)){m_verify.successful_positions_registered++;CaptureReport(plan,result);}else m_verify.metadata_registration_failures++;if(m_logger!=NULL)m_logger.Info("strategy=TREND_CONTINUATION, direction="+(plan.direction==E2_TC_LONG?"LONG":"SHORT")+", planId="+result.plan_id+", entry="+DoubleToString(result.actual_fill,spec.digits)+", SL="+DoubleToString(result.submitted_stop,spec.digits)+", TP="+DoubleToString(result.submitted_tp,spec.digits)+", volume="+DoubleToString(result.normalized_volume,4)+", riskCash="+DoubleToString(result.actual_initial_risk_cash,2)+", management="+E2V2ManagementBranchName(plan.management_branch)+", order="+StringFormat("%I64u",result.order_ticket)+", deal="+StringFormat("%I64u",result.deal_ticket),"V2_EXECUTION");return(true);
     }
   E2V2ExecutionVerification Verification()const{E2V2ExecutionVerification value=m_verify;value.unaccounted_valid_plans=value.valid_plans_received-value.execution_disabled-value.execution_successes-value.execution_failures;if(value.execution_attempts>0)value.average_planned_to_quote_difference=m_quote_diff_sum/value.execution_attempts;if(value.execution_successes>0){value.average_quote_to_fill_slippage=m_slippage_sum/value.execution_successes;value.average_actual_risk_cash=m_risk_sum/value.execution_successes;}return(value);}
   void Positions(E2V2PositionMetadata &values[])const{ArrayResize(values,ArraySize(m_metadata));for(int i=0;i<ArraySize(m_metadata);i++)values[i]=m_metadata[i];}
  };

#endif
