#ifndef E2_ANALYSIS_E2CONFIRMATIONANALYZER_MQH
#define E2_ANALYSIS_E2CONFIRMATIONANALYZER_MQH
#include "E2MarketData.mqh"
enum E2ConfirmationDirection { E2_CONFIRMATION_NONE,E2_CONFIRMATION_BULLISH,E2_CONFIRMATION_BEARISH };
enum E2ConfirmationReadiness { E2_CONFIRMATION_VALID,E2_CONFIRMATION_NOT_READY,E2_CONFIRMATION_NO_CONFIRMATIONS_ENABLED,E2_CONFIRMATION_DATA_ERROR };
struct E2ConfirmationResult { datetime evaluation_time,candle_time; E2ConfirmationDirection direction,engulfing,pin_bar,momentum,previous_break; E2ConfirmationReadiness readiness; bool directional_conflict; int bullish_passed,bearish_passed,required_bars,available_bars; string reason; };
string E2ConfirmationDirectionName(E2ConfirmationDirection d){return(d==E2_CONFIRMATION_BULLISH?"BULLISH":(d==E2_CONFIRMATION_BEARISH?"BEARISH":"NO"));}
string E2ConfirmationReadinessName(E2ConfirmationReadiness r){return(r==E2_CONFIRMATION_VALID?"VALID":(r==E2_CONFIRMATION_NO_CONFIRMATIONS_ENABLED?"NO_CONFIRMATIONS_ENABLED":(r==E2_CONFIRMATION_DATA_ERROR?"DATA_ERROR":"NOT_READY")));}
class E2ConfirmationAnalyzer
 {private:E2MarketData *m_market;bool m_engulf,m_pin,m_momentum,m_break;double m_min_wick,m_max_opposite,m_multiplier;int m_momentum_lookback;
 bool Valid(const MqlRates &b)const{return(MathIsValidNumber(b.open)&&MathIsValidNumber(b.high)&&MathIsValidNumber(b.low)&&MathIsValidNumber(b.close)&&b.high>=b.low);}
 E2ConfirmationDirection Engulfing(const MqlRates &c,const MqlRates &p)const{if(c.close>c.open&&p.close<p.open&&c.open<=p.close&&c.close>=p.open)return(E2_CONFIRMATION_BULLISH);if(c.close<c.open&&p.close>p.open&&c.open>=p.close&&c.close<=p.open)return(E2_CONFIRMATION_BEARISH);return(E2_CONFIRMATION_NONE);}
 E2ConfirmationDirection Pin(const MqlRates &c)const{double body=MathAbs(c.close-c.open);if(body<=0.0)return(E2_CONFIRMATION_NONE);double up=c.high-MathMax(c.open,c.close),down=MathMin(c.open,c.close)-c.low;if(down>=body*m_min_wick&&up<=body*m_max_opposite)return(E2_CONFIRMATION_BULLISH);if(up>=body*m_min_wick&&down<=body*m_max_opposite)return(E2_CONFIRMATION_BEARISH);return(E2_CONFIRMATION_NONE);}
 E2ConfirmationDirection Momentum(const MqlRates &b[],const int current)const{double total=0.0;for(int i=current-m_momentum_lookback;i<current;i++)total+=MathAbs(b[i].close-b[i].open);double body=MathAbs(b[current].close-b[current].open);if(body<total/m_momentum_lookback*m_multiplier)return(E2_CONFIRMATION_NONE);return(b[current].close>b[current].open?E2_CONFIRMATION_BULLISH:(b[current].close<b[current].open?E2_CONFIRMATION_BEARISH:E2_CONFIRMATION_NONE));}
 E2ConfirmationDirection PreviousBreak(const MqlRates &c,const MqlRates &p)const{return(c.close>p.high?E2_CONFIRMATION_BULLISH:(c.close<p.low?E2_CONFIRMATION_BEARISH:E2_CONFIRMATION_NONE));}
 void Count(const E2ConfirmationDirection d,E2ConfirmationResult &r)const{if(d==E2_CONFIRMATION_BULLISH)r.bullish_passed++;else if(d==E2_CONFIRMATION_BEARISH)r.bearish_passed++;}
 public:E2ConfirmationAnalyzer(void):m_market(NULL),m_engulf(false),m_pin(false),m_momentum(false),m_break(false),m_min_wick(0),m_max_opposite(0),m_multiplier(0),m_momentum_lookback(0){}
 void Initialize(const E2Config &c,E2MarketData &m){m_market=&m;m_engulf=c.enable_engulfing_confirmation;m_pin=c.enable_pin_bar_confirmation;m_momentum=c.enable_momentum_candle_confirmation;m_break=c.enable_break_previous_candle_confirmation;m_min_wick=c.pin_bar_minimum_wick_to_body_ratio;m_max_opposite=c.pin_bar_maximum_opposite_wick_to_body_ratio;m_momentum_lookback=c.momentum_body_lookback;m_multiplier=c.momentum_body_multiplier;}
 bool Evaluate(const string symbol,const datetime evaluation,E2ConfirmationResult &r){ZeroMemory(r);r.evaluation_time=evaluation;r.direction=E2_CONFIRMATION_NONE;r.engulfing=r.pin_bar=r.momentum=r.previous_break=E2_CONFIRMATION_NONE;r.readiness=E2_CONFIRMATION_NOT_READY;if(m_market==NULL){r.reason="MARKET_DATA_UNAVAILABLE";return(false);}if(!m_engulf&&!m_pin&&!m_momentum&&!m_break){r.readiness=E2_CONFIRMATION_NO_CONFIRMATIONS_ENABLED;r.reason="NO_CONFIRMATIONS_ENABLED";return(true);}r.required_bars=(m_momentum?m_momentum_lookback+1:2);MqlRates bars[];if(!m_market.GetClosedBarsAsOf(symbol,m_market.ConfirmationTimeframe(),evaluation,r.required_bars,bars)){r.reason=(m_momentum?"INSUFFICIENT_MOMENTUM_HISTORY":"INSUFFICIENT_CLOSED_CANDLE_HISTORY");return(false);}r.available_bars=ArraySize(bars);int c=ArraySize(bars)-1,p=c-1;if(c<1){r.reason="INSUFFICIENT_CLOSED_CANDLE_HISTORY";return(false);}for(int i=0;i<ArraySize(bars);i++)if(!Valid(bars[i])){r.readiness=E2_CONFIRMATION_DATA_ERROR;r.reason="INVALID_OHLC";return(false);}r.candle_time=bars[c].time;if(m_engulf){r.engulfing=Engulfing(bars[c],bars[p]);Count(r.engulfing,r);}if(m_pin){r.pin_bar=Pin(bars[c]);Count(r.pin_bar,r);}if(m_momentum){r.momentum=Momentum(bars,c);Count(r.momentum,r);}if(m_break){r.previous_break=PreviousBreak(bars[c],bars[p]);Count(r.previous_break,r);}r.readiness=E2_CONFIRMATION_VALID;if(r.bullish_passed>0&&r.bearish_passed>0){r.directional_conflict=true;r.direction=E2_CONFIRMATION_NONE;}else if(r.bullish_passed>0)r.direction=E2_CONFIRMATION_BULLISH;else if(r.bearish_passed>0)r.direction=E2_CONFIRMATION_BEARISH;r.reason="READY";return(true);} };
#endif
