#ifndef E2_ANALYSIS_E2TRENDCONTINUATIONENGINE_MQH
#define E2_ANALYSIS_E2TRENDCONTINUATIONENGINE_MQH
#include "E2H4RegimeEngine.mqh"
#include "E2H1ZoneEngine.mqh"
#include "E2M15ConfirmationEngine.mqh"
enum E2TrendContinuationState{E2_TC_IDLE,E2_TC_BREAKOUT_ACCEPTED,E2_TC_WAITING_FOR_RETEST,E2_TC_RETEST_ACTIVE,E2_TC_CONFIRMED,E2_TC_CONSUMED,E2_TC_INVALIDATED};
enum E2TrendContinuationDirection{E2_TC_LONG,E2_TC_SHORT};
string E2TrendContinuationStateName(const E2TrendContinuationState v){string n[]={"IDLE","BREAKOUT_ACCEPTED","WAITING_FOR_RETEST","RETEST_ACTIVE","CONFIRMED","CONSUMED","INVALIDATED"};return(n[(int)v]);}
string E2TrendContinuationDirectionName(const E2TrendContinuationDirection v){return(v==E2_TC_LONG?"LONG":"SHORT");}
struct E2TrendContinuationCandidate{string candidate_id,source_zone_id,invalidation_reason;E2StrategyType strategy_type;E2TrendContinuationDirection direction;E2TrendContinuationState state;datetime candidate_time,candidate_known_from_time,source_zone_creation_time,breakout_time,breakout_known_from_time,retest_time,retest_known_from_time;E2H1ZoneV2Type original_role,flipped_role;double zone_lower,zone_upper,breakout_close,breakout_atr,breakout_distance,breakout_distance_atr,confirmation_h1_atr;E2RegimeType h4_regime_at_creation,h4_regime_at_confirmation;bool trend_entry_eligible,overextended;double h4_ema20,h4_ema50,h4_ema50_slope,h4_adx,h4_atr,h4_extension_atr;int attempt_number;E2M15ConfirmationResult confirmation;};
struct E2TrendContinuationRecord{string zone_id,reason;E2TrendContinuationDirection direction;E2TrendContinuationState state;datetime transition_time,breakout_time,breakout_known_from_time,retest_time,retest_known_from_time;double lower,upper,breakout_close,breakout_atr;int attempt_number;bool approached_from_correct_side,inside_visit;};
struct E2TrendContinuationVerification{int break_long,break_short,retest_long,retest_short,confirm_long,confirm_short,candidate_long,candidate_short,duplicate_suppressed,h4_loss,h4_overextended,flipped_invalid,total,unique_attempts,duplicate_candidates,confirmation_timestamps_with_multiple_claimants,maximum_claimants_one_confirmation,ownership_resolutions,same_confirmation_multiple_candidates,causal_order_violations;};
struct E2TCGateDiagnostics{long h1_bars,uptrend,downtrend,eligible,resistance_bar,support_bar,resistance_observations,support_observations,resistance_checks,support_checks,above_edge,below_edge,distance_long,distance_short,zero_zone,nonzero_zone,max_zones,max_support,max_resistance,tc_calls,active_state_evaluations,confirmation_contexts,momentum_long,momentum_short;ulong h1_breakout_zone_checks,m15_state_checks,record_lookup_checks;};
struct E2TrendContinuationClaim{int record_index,zone_index;double edge_distance;E2M15ConfirmationResult confirmation;};
class E2TrendContinuationEngine{
private:
 E2MarketData *m_market;E2Logger *m_logger;E2M15ConfirmationEngine *m_confirmation;bool m_enabled,m_verbose;double m_break_atr,m_invalidation_atr;int m_h1_atr_period;datetime m_last_m15,m_last_gate_h1;E2TrendContinuationRecord m_records[];string m_record_keys[];int m_record_indices[];E2TrendContinuationVerification m_verify;E2TCGateDiagnostics m_gates;string m_emitted_attempts[],m_emitted_confirmation_times[];
 double Eps(double x)const{return(MathMax(1e-10,MathAbs(x)*1e-10));}bool GE(double a,double b)const{return(a>b||MathAbs(a-b)<=Eps(b));}bool Below(double a,double b)const{return(a<b-Eps(b));}bool Above(double a,double b)const{return(a>b+Eps(b));}
 string RecordKey(string id,E2TrendContinuationDirection d)const{return(id+"#"+IntegerToString((int)d));}
 int Find(string id,E2TrendContinuationDirection d){const string key=RecordKey(id,d);int lo=0,hi=ArraySize(m_record_keys)-1;while(lo<=hi){m_gates.record_lookup_checks++;const int mid=(lo+hi)/2,cmp=StringCompare(m_record_keys[mid],key);if(cmp==0)return(m_record_indices[mid]);if(cmp<0)lo=mid+1;else hi=mid-1;}return(-1);}
 void IndexRecord(string id,E2TrendContinuationDirection d,int record){const string key=RecordKey(id,d);int lo=0,hi=ArraySize(m_record_keys)-1;while(lo<=hi){const int mid=(lo+hi)/2,cmp=StringCompare(m_record_keys[mid],key);if(cmp==0)return;if(cmp<0)lo=mid+1;else hi=mid-1;}const int n=ArraySize(m_record_keys);ArrayResize(m_record_keys,n+1);ArrayResize(m_record_indices,n+1);for(int i=n;i>lo;i--){m_record_keys[i]=m_record_keys[i-1];m_record_indices[i]=m_record_indices[i-1];}m_record_keys[lo]=key;m_record_indices[lo]=record;}
 bool Contains(const string &a[],string s)const{for(int i=0;i<ArraySize(a);i++)if(a[i]==s)return(true);return(false);}void Remember(string &a[],string s)const{if(Contains(a,s))return;int n=ArraySize(a);ArrayResize(a,n+1);a[n]=s;}void Add(E2TrendContinuationClaim &a[],const E2TrendContinuationClaim &c)const{int n=ArraySize(a);ArrayResize(a,n+1);a[n]=c;}
 void Log(const E2TrendContinuationRecord &r)const{if(m_logger!=NULL&&m_logger.IsDebugEnabled()&&m_verbose)m_logger.Debug("zone="+r.zone_id+", direction="+E2TrendContinuationDirectionName(r.direction)+", state="+E2TrendContinuationStateName(r.state)+", time="+TimeToString(r.transition_time,TIME_DATE|TIME_MINUTES)+", reason="+r.reason,"TrendContinuationV2");}
 void Atr(const MqlRates &b[],double &v[])const{ArrayResize(v,ArraySize(b));for(int i=0;i<ArraySize(b);i++)v[i]=0;double s=0;for(int i=1;i<ArraySize(b);i++){double t=MathMax(b[i].high-b[i].low,MathMax(MathAbs(b[i].high-b[i-1].close),MathAbs(b[i].low-b[i-1].close)));if(i<=m_h1_atr_period){s+=t;if(i==m_h1_atr_period)v[i]=s/m_h1_atr_period;}else{s=s-s/m_h1_atr_period+t;v[i]=s/m_h1_atr_period;}}}
 bool H4Valid(const E2H4RegimeResult &h,E2TrendContinuationDirection d)const{return(h.ready&&h.trend_entry_eligible&&!h.trend_overextended&&(d==E2_TC_LONG?h.regime==E2_REGIME_UPTREND:h.regime==E2_REGIME_DOWNTREND));}
 bool Wins(const E2TrendContinuationClaim &a,const E2TrendContinuationClaim &b)const{if(a.edge_distance<b.edge_distance-Eps(b.edge_distance))return(true);if(a.edge_distance>b.edge_distance+Eps(b.edge_distance))return(false);datetime x=m_records[a.record_index].breakout_known_from_time,y=m_records[b.record_index].breakout_known_from_time;if(x!=y)return(x<y);return(m_records[a.record_index].zone_id<m_records[b.record_index].zone_id);}
 void Emit(E2TrendContinuationCandidate &o[],const E2TrendContinuationRecord &r,const E2H1ZoneV2Record &z,const E2H4RegimeResult &h,const E2M15ConfirmationResult &c,const double frozen_h1_atr)const{int n=ArraySize(o);ArrayResize(o,n+1);E2TrendContinuationCandidate v;ZeroMemory(v);v.candidate_id="TC_"+r.zone_id+"_"+IntegerToString((int)c.known_from_time);v.source_zone_id=r.zone_id;v.strategy_type=E2_STRATEGY_TREND_CONTINUATION;v.direction=r.direction;v.state=E2_TC_CONSUMED;v.candidate_time=c.candle_time;v.candidate_known_from_time=c.known_from_time;v.source_zone_creation_time=z.creation_time;v.breakout_time=r.breakout_time;v.breakout_known_from_time=r.breakout_known_from_time;v.retest_time=r.retest_time;v.retest_known_from_time=r.retest_known_from_time;v.original_role=z.type;v.flipped_role=(r.direction==E2_TC_LONG?E2_H1_ZONE_V2_SUPPORT:E2_H1_ZONE_V2_RESISTANCE);v.zone_lower=r.lower;v.zone_upper=r.upper;v.breakout_close=r.breakout_close;v.breakout_atr=r.breakout_atr;v.breakout_distance=(r.direction==E2_TC_LONG?r.breakout_close-r.upper:r.lower-r.breakout_close);v.breakout_distance_atr=(r.breakout_atr>0?v.breakout_distance/r.breakout_atr:0);v.confirmation_h1_atr=frozen_h1_atr;v.h4_regime_at_creation=h.regime;v.h4_regime_at_confirmation=h.regime;v.trend_entry_eligible=h.trend_entry_eligible;v.overextended=h.trend_overextended;v.h4_ema20=h.ema20;v.h4_ema50=h.ema50;v.h4_ema50_slope=h.ema50-h.ema50_five_bars_ago;v.h4_adx=h.adx;v.h4_atr=h.atr;v.h4_extension_atr=h.distance_close_to_ema20_atr;v.attempt_number=r.attempt_number;v.confirmation=c;o[n]=v;}
public:
 E2TrendContinuationEngine(void):m_market(NULL),m_logger(NULL),m_confirmation(NULL),m_enabled(false),m_verbose(false),m_break_atr(.1),m_invalidation_atr(.1),m_h1_atr_period(14),m_last_m15(0),m_last_gate_h1(0){ZeroMemory(m_verify);ZeroMemory(m_gates);}
 void Initialize(const E2Config &c,E2MarketData &m,E2M15ConfirmationEngine &x,E2Logger &l){m_market=&m;m_confirmation=&x;m_logger=&l;m_enabled=c.enable_trend_continuation;m_verbose=c.research_verbose_diagnostics;m_break_atr=c.research_h1_breakout_distance_atr;m_invalidation_atr=c.research_h1_zone_invalidation_atr;m_h1_atr_period=c.research_h1_atr_period;m_last_m15=0;m_last_gate_h1=0;ArrayResize(m_records,0);ArrayResize(m_record_keys,0);ArrayResize(m_record_indices,0);ArrayResize(m_emitted_attempts,0);ArrayResize(m_emitted_confirmation_times,0);ZeroMemory(m_verify);ZeroMemory(m_gates);}
 E2TrendContinuationVerification Verification(void)const{return(m_verify);}E2TCGateDiagnostics Gates(void)const{return(m_gates);}
 bool Evaluate(const string symbol,const datetime e,const E2H4RegimeResult &h,const E2H1ZoneV2Record &z[],E2TrendContinuationCandidate &out[]){
  ArrayResize(out,0);m_gates.tc_calls++;if(!m_enabled||m_market==NULL||m_confirmation==NULL)return(true);MqlRates m;if(!m_market.GetClosedBarAsOf(symbol,PERIOD_M15,e,m)||m.time==m_last_m15)return(true);m_last_m15=m.time;datetime mk=m.time+PeriodSeconds(PERIOD_M15);MqlRates b[];if(!m_market.GetClosedBarsAsOf(symbol,PERIOD_H1,e,240,b))return(false);double a[];Atr(b,a);int last=ArraySize(b)-1;datetime hk=b[last].time+PeriodSeconds(PERIOD_H1);
  const bool new_h1=(hk!=m_last_gate_h1);if(new_h1){m_last_gate_h1=hk;m_gates.h1_bars++;if(h.regime==E2_REGIME_UPTREND)m_gates.uptrend++;if(h.regime==E2_REGIME_DOWNTREND)m_gates.downtrend++;if(h.trend_entry_eligible)m_gates.eligible++;int ac=0,su=0,re=0;for(int q=0;q<ArraySize(z);q++)if(z[q].state==E2_H1_ZONE_V2_ACTIVE){ac++;if(z[q].type==E2_H1_ZONE_V2_SUPPORT)su++;else re++;}if(ac==0)m_gates.zero_zone++;else m_gates.nonzero_zone++;if(su)m_gates.support_bar++;if(re)m_gates.resistance_bar++;m_gates.support_observations+=su;m_gates.resistance_observations+=re;m_gates.max_zones=MathMax(m_gates.max_zones,ac);m_gates.max_support=MathMax(m_gates.max_support,su);m_gates.max_resistance=MathMax(m_gates.max_resistance,re);}
  E2TrendContinuationClaim claims[];
  for(int i=0;i<ArraySize(z);i++){const E2H1ZoneV2Record zone=z[i];E2TrendContinuationDirection d=(zone.type==E2_H1_ZONE_V2_RESISTANCE?E2_TC_LONG:E2_TC_SHORT);if(new_h1){m_gates.h1_breakout_zone_checks++;if(d==E2_TC_LONG){m_gates.resistance_checks++;if(b[last].close>zone.upper)m_gates.above_edge++;if(a[last]>0&&GE(b[last].close,zone.upper+m_break_atr*a[last]))m_gates.distance_long++;}else{m_gates.support_checks++;if(b[last].close<zone.lower)m_gates.below_edge++;if(a[last]>0&&GE(zone.lower-m_break_atr*a[last],b[last].close))m_gates.distance_short++;}}int at=Find(zone.zone_id,d);if(at<0){at=ArraySize(m_records);ArrayResize(m_records,at+1);ZeroMemory(m_records[at]);m_records[at].zone_id=zone.zone_id;m_records[at].direction=d;m_records[at].state=E2_TC_IDLE;m_records[at].lower=zone.lower;m_records[at].upper=zone.upper;IndexRecord(zone.zone_id,d,at);}E2TrendContinuationRecord r=m_records[at];if(r.state==E2_TC_CONSUMED||r.state==E2_TC_INVALIDATED)continue;if(r.state==E2_TC_IDLE&&!new_h1)continue;m_gates.m15_state_checks++;
   if(!H4Valid(h,d)){if(r.state!=E2_TC_IDLE){r.state=E2_TC_INVALIDATED;r.transition_time=mk;r.reason="H4_REGIME_LOST_OR_INELIGIBLE";if(h.trend_overextended)m_verify.h4_overextended++;else m_verify.h4_loss++;Log(r);}m_records[at]=r;continue;}
   bool br=(a[last]>0&&zone.creation_time<hk&&((d==E2_TC_LONG&&GE(b[last].close,zone.upper+m_break_atr*a[last]))||(d==E2_TC_SHORT&&GE(zone.lower-m_break_atr*a[last],b[last].close))));if(r.state==E2_TC_IDLE&&br){r.state=E2_TC_WAITING_FOR_RETEST;r.transition_time=hk;r.breakout_time=b[last].time;r.breakout_known_from_time=hk;r.breakout_close=b[last].close;r.breakout_atr=a[last];r.retest_time=0;r.retest_known_from_time=0;r.attempt_number=0;r.approached_from_correct_side=false;r.inside_visit=false;if(d==E2_TC_LONG)m_verify.break_long++;else m_verify.break_short++;r.reason="BREAKOUT_ACCEPTED";Log(r);}
   if(r.state==E2_TC_WAITING_FOR_RETEST||r.state==E2_TC_RETEST_ACTIVE){if(a[last]>0&&((d==E2_TC_LONG&&Below(b[last].close,zone.lower-m_invalidation_atr*a[last]))||(d==E2_TC_SHORT&&Above(b[last].close,zone.upper+m_invalidation_atr*a[last])))){r.state=E2_TC_INVALIDATED;r.transition_time=hk;r.reason="FLIPPED_ZONE_INVALIDATED";m_verify.flipped_invalid++;Log(r);m_records[at]=r;continue;}if(mk<=r.breakout_known_from_time){m_records[at]=r;continue;}bool overlap=(m.low<=r.upper&&m.high>=r.lower);if(!r.approached_from_correct_side&&!overlap){if(d==E2_TC_LONG?m.low>r.upper:m.high<r.lower)r.approached_from_correct_side=true;}if(overlap&&r.approached_from_correct_side&&!r.inside_visit){r.inside_visit=true;r.state=E2_TC_RETEST_ACTIVE;r.retest_time=m.time;r.retest_known_from_time=mk;r.attempt_number++;r.transition_time=mk;if(d==E2_TC_LONG)m_verify.retest_long++;else m_verify.retest_short++;r.reason="RETEST_ACTIVE";Log(r);}else if(!overlap)r.inside_visit=false;
    if(r.state==E2_TC_RETEST_ACTIVE&&mk>=r.retest_known_from_time){E2M15ZoneContext c;c.zone_id=zone.zone_id;c.type=(d==E2_TC_LONG?E2_H1_ZONE_V2_SUPPORT:E2_H1_ZONE_V2_RESISTANCE);c.state=E2_H1_ZONE_V2_ACTIVE;c.lower=r.lower;c.upper=r.upper;c.creation_time=zone.creation_time;c.invalidation_time=0;E2M15ConfirmationResult rs[];m_gates.confirmation_contexts++;if(m_confirmation.Evaluate(symbol,e,c,rs)){int w=(d==E2_TC_LONG?0:1);if(rs[w].passed){if(!(r.breakout_known_from_time<r.retest_known_from_time&&r.retest_known_from_time<=rs[w].known_from_time))m_verify.causal_order_violations++;else{E2TrendContinuationClaim cl;cl.record_index=at;cl.zone_index=i;cl.confirmation=rs[w];cl.edge_distance=(d==E2_TC_LONG?MathAbs(rs[w].close-r.upper):MathAbs(r.lower-rs[w].close));Add(claims,cl);}}}}
   }m_records[at]=r;}
  if(ArraySize(claims)>0){if(ArraySize(claims)>1){m_verify.confirmation_timestamps_with_multiple_claimants++;m_verify.maximum_claimants_one_confirmation=MathMax(m_verify.maximum_claimants_one_confirmation,ArraySize(claims));m_verify.ownership_resolutions++;}int win=0;for(int i=1;i<ArraySize(claims);i++)if(Wins(claims[i],claims[win]))win=i;E2TrendContinuationClaim cl=claims[win];E2TrendContinuationRecord r=m_records[cl.record_index];string attempt=r.zone_id+"#"+IntegerToString(r.attempt_number),key=IntegerToString((int)cl.confirmation.known_from_time);if(Contains(m_emitted_attempts,attempt)){m_verify.duplicate_suppressed++;m_verify.duplicate_candidates++;}else{if(Contains(m_emitted_confirmation_times,key))m_verify.same_confirmation_multiple_candidates++;Remember(m_emitted_attempts,attempt);Remember(m_emitted_confirmation_times,key);m_verify.unique_attempts++;m_verify.total++;if(r.direction==E2_TC_LONG){m_verify.confirm_long++;m_verify.candidate_long++;}else{m_verify.confirm_short++;m_verify.candidate_short++;}Emit(out,r,z[cl.zone_index],h,cl.confirmation,a[last]);}r.state=E2_TC_CONSUMED;r.transition_time=cl.confirmation.known_from_time;r.reason="CONFIRMED_CONSUMED";Log(r);m_records[cl.record_index]=r;}
  return(true);}
};
#endif
