#ifndef E2_ANALYSIS_E2ZONEANALYZER_MQH
#define E2_ANALYSIS_E2ZONEANALYZER_MQH
#include "E2MarketData.mqh"
#include "..\\core\\E2SymbolInfo.mqh"
enum E2ZoneType { E2_ZONE_SUPPORT,E2_ZONE_RESISTANCE };
enum E2ZoneState { E2_ZONE_CANDIDATE,E2_ZONE_ACTIVE,E2_ZONE_BROKEN_AWAITING_RETEST,E2_ZONE_ROLE_REVERSED_ACTIVE,E2_ZONE_INVALIDATED };
struct E2Zone { int id; E2ZoneType type,origin_type; E2ZoneState state; bool actionable; double lower,upper,center; int touches; datetime origin_time,known_from_time,last_touch_time,break_time,reversal_time; };
string E2ZoneTypeName(const E2ZoneType t){return(t==E2_ZONE_SUPPORT ? "SUPPORT" : "RESISTANCE");}
string E2ZoneStateName(const E2ZoneState s){if(s==E2_ZONE_ACTIVE)return("ACTIVE");if(s==E2_ZONE_BROKEN_AWAITING_RETEST)return("BROKEN_AWAITING_RETEST");if(s==E2_ZONE_ROLE_REVERSED_ACTIVE)return("ROLE_REVERSED_ACTIVE");if(s==E2_ZONE_INVALIDATED)return("INVALIDATED");return("CANDIDATE");}
class E2ZoneAnalyzer
 {private:E2MarketData *m_market;E2SymbolInfo *m_symbol;int m_sensitivity,m_lookback,m_min;double m_tol,m_merge;
 bool Pivot(const MqlRates &b[],int i,bool high)const{double v=high?b[i].high:b[i].low;for(int k=1;k<=m_sensitivity;k++)if(high?(v<=b[i-k].high||v<=b[i+k].high):(v>=b[i-k].low||v>=b[i+k].low))return(false);return(true);}
 bool Compatible(const E2Zone &z,E2ZoneType t,double level,double width,double merge)const{if(z.state==E2_ZONE_INVALIDATED)return(false);if(z.origin_type!=t&&z.type!=t)return(false);double l=level-width,u=level+width,gap=(u<z.lower?z.lower-u:(l>z.upper?l-z.upper:0));return(gap<=merge&&MathAbs(level-z.center)<=width+merge);}
 void Candidate(E2Zone &z[],E2ZoneType t,double level,datetime pivot,datetime known,double width,double merge,int &next)const{int f=-1;for(int i=0;i<ArraySize(z);i++)if(Compatible(z[i],t,level,width,merge)){f=i;break;}if(f<0){f=ArraySize(z);ArrayResize(z,f+1);z[f].id=next++;z[f].type=t;z[f].origin_type=t;z[f].state=E2_ZONE_CANDIDATE;z[f].actionable=false;z[f].center=level;z[f].origin_time=pivot;z[f].known_from_time=known;z[f].touches=1;z[f].last_touch_time=pivot;z[f].break_time=0;z[f].reversal_time=0;}else z[f].center=(z[f].center+level)/2.0;z[f].lower=m_symbol.NormalizePrice(z[f].center-width);z[f].upper=m_symbol.NormalizePrice(z[f].center+width);}
 bool Actionable(const E2Zone &z)const{return(z.state==E2_ZONE_ACTIVE||z.state==E2_ZONE_ROLE_REVERSED_ACTIVE);}
 bool DuplicateActionable(const E2Zone &a,const E2Zone &b,const double width,const double merge)const{if(a.type!=b.type)return(false);double gap=(a.upper<b.lower?b.lower-a.upper:(b.upper<a.lower?a.lower-b.upper:0));return(gap<=merge&&MathAbs(a.center-b.center)<=width+merge);}
 bool Prefer(const E2Zone &a,const E2Zone &b)const{int ap=(a.state==E2_ZONE_ROLE_REVERSED_ACTIVE?1:0),bp=(b.state==E2_ZONE_ROLE_REVERSED_ACTIVE?1:0);if(ap!=bp)return(ap>bp);if(a.touches!=b.touches)return(a.touches>b.touches);if(a.last_touch_time!=b.last_touch_time)return(a.last_touch_time>b.last_touch_time);return(a.id<b.id);}
 void FinalizeActionable(E2Zone &z[],const double width,const double merge)const{for(int i=0;i<ArraySize(z);i++)z[i].actionable=Actionable(z[i]);for(int i=0;i<ArraySize(z);i++){if(!z[i].actionable)continue;for(int j=i+1;j<ArraySize(z);j++){if(!z[i].actionable||!z[j].actionable||!DuplicateActionable(z[i],z[j],width,merge))continue;if(Prefer(z[i],z[j]))z[j].actionable=false;else z[i].actionable=false;}}}
 void Replay(E2Zone &z,const MqlRates &b[])const{bool inside=false;for(int i=0;i<ArraySize(b);i++){if(b[i].time<z.known_from_time)continue;bool hit=(b[i].low<=z.upper&&b[i].high>=z.lower);if(hit&&!inside){z.touches++;z.last_touch_time=b[i].time;}inside=hit;if(z.state==E2_ZONE_CANDIDATE&&z.touches>=m_min)z.state=E2_ZONE_ACTIVE;if(z.state==E2_ZONE_ACTIVE){if((z.type==E2_ZONE_SUPPORT&&b[i].close<z.lower)||(z.type==E2_ZONE_RESISTANCE&&b[i].close>z.upper)){z.state=E2_ZONE_BROKEN_AWAITING_RETEST;z.break_time=b[i].time;}}else if(z.state==E2_ZONE_BROKEN_AWAITING_RETEST&&b[i].time>z.break_time&&hit){bool reject=(z.origin_type==E2_ZONE_SUPPORT?b[i].close<=z.upper:b[i].close>=z.lower);if(reject){z.type=(z.origin_type==E2_ZONE_SUPPORT?E2_ZONE_RESISTANCE:E2_ZONE_SUPPORT);z.state=E2_ZONE_ROLE_REVERSED_ACTIVE;z.reversal_time=b[i].time;}}else if(z.state==E2_ZONE_ROLE_REVERSED_ACTIVE){if((z.type==E2_ZONE_SUPPORT&&b[i].close<z.lower)||(z.type==E2_ZONE_RESISTANCE&&b[i].close>z.upper))z.state=E2_ZONE_INVALIDATED;}}}
 public:E2ZoneAnalyzer(void):m_market(NULL),m_symbol(NULL),m_sensitivity(0),m_lookback(0),m_min(0),m_tol(0),m_merge(0){}
 void Initialize(const E2Config &c,E2MarketData &m,E2SymbolInfo &s){m_market=&m;m_symbol=&s;m_sensitivity=c.swing_sensitivity;m_lookback=c.zone_lookback_bars;m_min=c.minimum_zone_touches;m_tol=c.zone_tolerance_pips;m_merge=c.zone_merge_tolerance_pips;}
 bool Evaluate(const string symbol,datetime t,E2Zone &z[],int &candidates){ArrayResize(z,0);candidates=0;if(m_market==NULL||m_symbol==NULL||!m_symbol.IsInitialized())return(false);MqlRates b[];if(!m_market.GetClosedBarsAsOf(symbol,m_market.ZoneTimeframe(),t,m_lookback,b))return(false);E2SymbolSpecification s=m_symbol.Specification();double w=m_tol*s.pip_size,mg=m_merge*s.pip_size;int next=1;for(int i=m_sensitivity*2;i<ArraySize(b);i++){int p=i-m_sensitivity;datetime known=b[i].time+PeriodSeconds(m_market.ZoneTimeframe());if(Pivot(b,p,false)){Candidate(z,E2_ZONE_SUPPORT,b[p].low,b[p].time,known,w,mg,next);candidates++;}if(Pivot(b,p,true)){Candidate(z,E2_ZONE_RESISTANCE,b[p].high,b[p].time,known,w,mg,next);candidates++;}}for(int i=0;i<ArraySize(z);i++)Replay(z[i],b);FinalizeActionable(z,w,mg);return(true);} };
#endif
